### ISSUE TITLE
Mongock reexecutes ChangeSet on every run

### ISSUE THREAD

**Issue by minogin** [cloudyrock/mongock#107]
In version 3.0.8 Mongock does not respect changelog reexecuting already executed change sets on every run (despite "runAlways" is false). In 2.0.2 everything is OK.
BTW I don't use "version" field, only "id".

**Comment by dieppa** [comment]
thanks. We added some changes around that which may affect. Also we had to disable the tests because fongo is not compatible with last version of mongod driver.

Anyway, that will be fixed for 2nd Jan

**Comment by dieppa** [comment]
I actually just fixed and added some tests to cover it, check out 3.1.0.BETA

FYI: We enabled the tests again by adding testcontainers, but there is still some work to do on them. Once that is done and we are confident, we'll release a RC
