### ISSUE TITLE
MongoTemplate argument in changeset's method doesn't work (Dropwizard)

### ISSUE THREAD

**Issue by pjonastik** [cloudyrock/mongock#123]
I use _Dropwizard_ and _Spring Data_ in our project and _Mongock_. Migration tool works fine when changeset methods contains **com.mongodb.client.MongoDatabase**, but when I  have tried it use with Spring's **MongoTemplate** argument as your documentations propose:

`@ChangeSet(order = "005", id = "someChangeWithSpringDataTemplate", author = "testAuthor")
public void someChange5(MongoTemplate mongoTemplate) {
  // type: org.springframework.data.mongodb.core.MongoTemplate
  // Spring Data integration allows using MongoTemplate in the ChangeSet
  // example:
  mongoTemplate.save(myEntity);
}`

I ended in ERROR with error message: **ChangeSet method has wrong arguments list. Please see docs for more info!** 

Then I have search in your code for this occurrence in your code and I found method called **Mongock.executeChangeSetMethod** where according to your code you do not support anything else then the **MongoDatabase**. So there are only two explanation for me: 
- You have obsolete documentation and do not support Spring Data.
- Is it not possible to run it with Dropwizard with Spring Data dependencies.

I also have learnt that in another dev team which use _MongoBeeJ_, Dropwizard and Spring Data they managed to run it with MongoTemplate argument in ChangeSet methods. I would rather not migrate to another library because of this. I would be more than happy to hear any helpful information from your side.

**Dependencies:**
- io.dropwizard:dropwizard-core:jar:1.3.12
- org.mongodb:mongo-java-driver:jar:3.11.0
- org.springframework.data:spring-data-mongodb:jar:1.10.18.RELEASE
- com.github.cloudyrock.mongock:mongock-core:2.0.2
- com.github.cloudyrock.mongock:mongock-spring:jar:2.0.2

**Comment by dieppa** [comment]
Hello, it's weird MongoTemplate doesn't work. That sounds like a bug, but no one has reported and I have been using MongoTemplate myself without Dorpwizard, but that shouldn't affect.
We will have a look asap, but we cannot commit before the weekend.

However, could you try with the last BETA version: 3.2.2.BETA, please?

**Comment by dieppa** [comment]
Also, could you show me how are you building Mongock, there is a chance de error is there ;)

**Comment by dieppa** [comment]
Hello @pjonastik , that's weird.  I have been using MongoTemplate with that version myself and haven't got that issue. Actually I just run it.

It would really helpful if you can show me how you are building the Mongock object, hopefully there is something not quite right there.

Otherwise, we will have a look, but cannot commit before the end of the week. However, you could try the last BETA version(3.2.2.BETA) to discard things.

**Comment by alexciornii** [comment]
@pjonastik the **2.0.2** version has a bug. Please try to use the last BETA version **3.2.1.BETA**

**Comment by dieppa** [comment]
Thanks @alexciornii!
@pjonastik , we'll be updating the samples project to reflect this as well as the use of latest versions and integrations with other frameworks.

**Comment by pjonastik** [comment]
> @pjonastik the **2.0.2** version has a bug. Please try to use the last BETA version **3.2.1.BETA**
Thank you very much :)

**Comment by pjonastik** [comment]
@alexciornii thank you

**Comment by dieppa** [comment]
@pjonastik  anything else you struggle with, please let us know.
