### ISSUE TITLE
Use MongoTemplate rather than MongoClient to instantiate a new Mongock

### ISSUE THREAD

**Issue by santam85** [cloudyrock/mongock#127]
In SpringBoot projects, the only Bean we can autowire would be the MongoTemplate itself, from which seems pretty tricky (and pointless) to extract a new MongoClient. Please add the ability to instantiate a new Mongock directly with a MongoTemplate, at least for the SpringMongockBuilder.

**Comment by dieppa** [comment]
Hello @santam85 ,

it's a good suggestion and fairly easy. We'll make our best to have a release at the end of today.

Will let you know.

Thanks

**Comment by santam85** [comment]
Thanks for the quick reply, looking forward to it!

**Comment by dieppa** [comment]
Hello @santam85 ,

we have released version 3.2.2.BETA. 

I am closing this issue, however I'd really appreciate if you can let us know if everything is ok for you.

thanks

**Comment by santam85** [comment]
@dieppa I can confirm that this is working for me! Thanks a lot for the quick turnaround.

If that's ok for you, I'll try my hand at a PR soon to make the framework a little more spring-boot friendly (IE: use the spring context to resolve, instantiate and inject ChangeLogs rather than resort to pure reflection)

**Comment by dieppa** [comment]
Hello @santam85 ,

that sounds good, please feel free to do it and I will be more than happy to review it :)
