### ISSUE TITLE
default name of change log collection missleading in README.md

### ISSUE THREAD

**Issue by Endron** [cloudyrock/mongock#130]
In the README.md's Standalone section (https://github.com/cloudyrock/mongock/blob/master/README.md#standalone-usage) the default for the change log collection is given as "dbchangelog".

`builder.setChangelogCollectionName(logColName);   // default is dbchangelog, collection with applied change sets`

This seams to be incorrect for version 2.0.2 here the collection is called "mongockChangeLog" by default. (I did not check the source code for other versions.)

This documentation misled me when I was setting up Mongock last week.

**Comment by dieppa** [comment]
Hello @Endron ,
You are right, that's wrong in the documentation. As you say, the collection name is mongockChangeLock. That will be fixed in the documentation today, along any other issue.

Please, don't hesitate to ask me any question you have or if you need help.

**Comment by Endron** [comment]
@dieppa thanks for the amazingly fast response.
I do not need any further help from your side. After I found this it was easily fixed by just explicitly setting the collection name.

**Comment by dieppa** [comment]
Thanks @Endron. Just out of curious, why do you need to set a specific collectionName?

**Comment by Endron** [comment]
We are migrating from MongoBee (https://github.com/mongobee/mongobee) by setting the collection name it should be very much an in place update as mongobee stored all its changes in documents that look like Mongock's changelog documents. So my hope is that this will keep everything running as is.

**Comment by dieppa** [comment]
Ok, let me know if you fin any issue, because in the last versions we removed that setter. If that were the case, I would provide a fix, as it makes totally sense to keep for these cases.

**Comment by Endron** [comment]
I would encourage keeping the option to set the collection for the change log.
Being opinionated is fine and dandy. But you should always keep an option to get out of your carefully chosen defaults :wink: And if you remove it now you might be breaking backwards compatibility for anyone who is using it...

**Comment by dieppa** [comment]
Thanks again. That's enabled in the last version 3.2.3.BETA ;).

I close this issue. Anything else you need, please let us know
