### ISSUE TITLE
can't set lock collection name

### ISSUE THREAD

**Issue by raverone** [cloudyrock/mongock#139]
Currently it's not possible to change lock collection name for any mongock builder.
There is an example in readme telling how to do it, but it is wrong, there is no such method "setLockCollectionName" in any mongock builder.
Please add such method, so it can be used just like in readme.

**Comment by dieppa** [comment]
Can I ask what do you need to change the name of the lock collection?

**Comment by raverone** [comment]
I need multiple instances of mongock to work with same db. And I need them to not block each other.

**Comment by dieppa** [comment]
Hello @raverone, thanks, I wanted to understand your need. Sorry, but parallel processing is not possible right now due to an internal limitation related to Spring MongoTemplate.

However, this is something we have add to our roadmap for the next release, which will be published soon.

Meanwhile, I would like to know how bad is for you to run it sequentially?

Thanks

**Comment by martinnemec3** [comment]
Hello, I would also appreciate if the name of the lockCollection would be settable.

IMHO there can be multiple reasons for this, e.g. that a user wants to have maintenance-related collections names to follow some pattern (like '_' at the beginning, etc...)

Thanks.

**Comment by dieppa** [comment]
I see your points @martinnemec3  and @raverone, and I agree. We'll make this available, but we need to be quite visible and explicit that currently parallel processing is not possible.

Thanks, I'll keep you updated

**Comment by dieppa** [comment]
I think this can released tomorrow.

Meanwhile, @martinnemec3  @raverone   If it's not an inconvenient for you, could you take 1 minute to fill this small survey, please? It will help us a lot.

Thanks

**Comment by dieppa** [comment]
@raverone  and @martinnemec3 3.2.5 has been released and you have the method setLockCollectionName re-enabled.

A section referring to parallel processing has also been added to the readme. 

Thanks

**Comment by raverone** [comment]
Great, thanks! Did you post a link for the survey? Or am I missing something?

**Comment by raverone** [comment]
Oh, I got it :D
