### ISSUE TITLE
Try to bring custom params to changset but get argument not injected exception

### ISSUE THREAD

**Issue by lorschtan** [cloudyrock/mongock#140]
Sorry, I was new in mongo. 

I was try to create a changeset method with custom params (my mongo property class), but when run will get (Method [method name] using argument [custom mongo property class] not injected) exception. 

May I know how to inject my property class?

(using 3.2.4 version)

**Comment by dieppa** [comment]
Hello @lorschtan , could you provide a bit more information:
1) MongockSpring?
2) Can you provide the code of the changeSet, or at least the signature
3) anything you feel relevant

Thanks

**Comment by lorschtan** [comment]
yes, mongock spring.

```
<dependency>
	<groupId>com.github.cloudyrock.mongock</groupId>
	<artifactId>mongock-spring</artifactId>
	<version>3.2.4</version>
</dependency>

<dependency>
	<groupId>org.springframework.data</groupId>
	<artifactId>spring-data-mongodb</artifactId>
</dependency>
		    
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-mongodb</artifactId>
</dependency>
```

the maven for mongo
```

@Bean
	public SpringMongock mongock() {
		MongoClient mongoClient = new MongoClient(new MongoClientURI(this.mongodbUri));
		return new SpringMongockBuilder(mongoClient, this.mongoDb, this.packageNameToScan)
				.setLockQuickConfig()
				.build();
	}
```

this is the mongock config

```
@ChangeSet(order = "000", id = "init_setup", author = "lorsch")
	public void initSetup(MongoTemplate template, MongoConfig config) {
		(haven't start write anything yet)
	}
```
this is my changeset
he mongoconfig is my custom mongo config. i'm actually try to create a changeset that able to do create database, create collection, create user and set up db auth

**Comment by lorschtan** [comment]
i tried to bring params (mongo template, spring framework core environment), but the environment also having the same issue (not injected), is it required anthing else?

**Comment by dieppa** [comment]
Hello @lorschtan , you are not injecting the Spring Application context as you can see [here](https://github.com/cloudyrock/mongock#usage-with-springmongock-as-a-bean) .

Please try this an let me know how it goes ;)

**Comment by lorschtan** [comment]
@dieppa , Yea, It works. Thank you so much.

**Comment by dieppa** [comment]
Great @lorschtan , I am glad it worked :)
