### ISSUE TITLE
Is it possible to run mongock in multiple databases?

### ISSUE THREAD

**Issue by andrelanca** [cloudyrock/mongock#151]
Hello there,
I'm implementing Mongock in a multi tenant project and I want to iterate through all databases and create the SprintBootMongock object... But how can i create a Bean of SpringBootMongock for all my databases ? For one works perfectly, but for more i don't know how to implement multiple beans, because the number of databases are dynamic

**Comment by dieppa** [comment]
Hello @andrelanca , how are you managing the access to each database? Different MongoTemplates?

**Comment by andrelanca** [comment]
@dieppa already found a way, but thanks for your help :)

**Comment by dieppa** [comment]
What ever you found I would be cautious, Mongock right now doesn't support that and you can get some unpredictable result. However it's in our road map

**Comment by andrelanca** [comment]
Ok, I'll keep that in mind. Thank you :)
