### ISSUE TITLE
Missig setLockCollectionName in MongockBuilder (event SpringBoot version)

### ISSUE THREAD

**Issue by marchrius** [cloudyrock/mongock#158]
In the MongockBuilder and in SpringBootMongockBuilder there is no `setLockCollectionName` setter. In the README.md the setter is shown as usable but it does not exists.

Is the error related to missing method or to not updated README ?

**Comment by dieppa** [comment]
Hello @marchrius , what version are you using? You should be have it re-enable it since version 3.2.5.

Please, can you confirm?

**Comment by marchrius** [comment]
Hello @dieppa , you are right. I confirm that upgrading to 3.2.5 the method returned! Thank you and sorry for mistake! :)
