### ISSUE TITLE
mongock-samples 404

### ISSUE THREAD

**Issue by charlesritchea** [cloudyrock/mongock#174]
The mongock-samples project is either hidden or deleted

**Comment by dieppa** [comment]
Hello, you are right. It has been deleted. We are updating the readme and creating a new sam ple project.

What can we help you with?

**Comment by charlesritchea** [comment]
@dieppa I think I've figured it out, just filing issues as I go

**Comment by dieppa** [comment]
Cool, any help, just let us know ;)
