### ISSUE TITLE
mongock sample are gone

### ISSUE THREAD

**Issue by megasqrt** [cloudyrock/mongock#176]
https://github.com/cloudyrock/mongock-samples github 404 :(

**Comment by dieppa** [comment]
Hello, @megasqrt 

yes, you're right. The project wasn't up to date and therefore misleading users. We will be uploading them in these days, probably tomorrow. 

Meanwhile, is there anything we can help you with?

**Comment by megasqrt** [comment]
thanks, im found sample in branch v4_sample_spring_5_springdata_3

**Comment by dieppa** [comment]
take into account that uses version 4.0.x.alpha, which is available and I'd say pretty stable, but it's still an alpha, so I'd recommend it if you are going to production in the next few weeks.
