### ISSUE TITLE
Mongock 4 ALPHA breaks compatibility with mongobee

### ISSUE THREAD

**Issue by pkubowicz** [cloudyrock/mongock#177]
I can switch from using mongobee to Mongock 3 and then to Mongock 4 but I cannot directly switch from mongobee to Mongock 4 because my migrations will be applied again.

Also, I can switch from Mongock 4 to Mongock 3 and from Mongock 4 to mongobee, but not from Mongock 4 to Mongock 3 and then to mongobee.

See a working example in https://github.com/pkubowicz/mongock4

**Comment by dieppa** [comment]
Hello @pkubowicz ,

> I cannot directly switch from mongobee to Mongock 4 because my migrations will be applied again

You are right, we have this in our RoadMap. 
**Are you in in production, about to promote to it or it's urgent for some other reason? So we can prioritise and we could realise a new alpha version with this in it.**

> Also, I can switch from Mongock 4 to Mongock 3 and from Mongock 4 to mongobee, but not from Mongock 4 to Mongock 3 and then to mongobee

Sorry, but we don't guarantee this migration. Anyway, once moved to Mongock 4, why would you want to migrate back to Mongobee? I am curious

**Comment by pkubowicz** [comment]
It's not urgent. I'm still using mongobee and evaluating if it's safe for me to switch. In the long run I want to be able to use Spring Boot 2.3 which neither mongobee nor Mongock 3 allow.

What would be important for me is
- assuring that migrating between Mongock 3 and Mongock 4 (stable release) will be possible in both directions
- documenting whether migration directly from mongobee to Mongock 4 is possible or not

**Comment by dieppa** [comment]
Hello @pkubowicz ,

> assuring that migrating between Mongock 3 and Mongock 4 (stable release) will be possible in both directions

Assuming you mean the migration data, not the code itself...
- **from Mongock 3 to Mongock 4 > It will be done**, probably next week.
- **from Mongock 4 to Mongock 3 > In this case will be done too,** but you should keep in mind that this is normally not provided. For example, Spring could provide backward compatibility  for previous version(not even that, as they normally introduce breaking changes), but for sure they don't provide reverse compatibility.


> documenting whether migration directly from mongobee to Mongock 4 is possible or not

**It will be fully documented**

**Comment by dieppa** [comment]
Can I ask what type of project you are developing? 

thanks

**Comment by pkubowicz** [comment]
Being able to revert code to a previous version and run the old code on a database touched by the new code is very important - it gives you more safety when deploying to production, because if there is a bug, you simply roll back the deployment.

I agree you don't have to allow going back from Mongock 4 to mongobee as these are 2 'leaps'. Documenting that this is simply not possible is fine. However, I strongly believe that Mongock 4 should guarantee that you can rollback from Mongock 4 to Mongock 3.

My application is a back-end service based on Spring Boot and Mongo. The sample I provided is not representative - it does not start a web server, because I wanted the sample to provide quick feedback and stop working. If I see a stable release of Mongock 4 that will guarantee backward compatibility of data with Mongock 3, I will first deploy my app updated to Mongock 3 and then deploy an update to Mongock 4 - this way I will be able to safely rollback each of 2 deployments.

**Comment by dieppa** [comment]
I understand what you are saying. 
> You can assume we'll provide the following out of the box:

- Migration from Mongock 3 to Mongock 4 
- Migration from Mongobee to Mongock 4 
- Migration from MongoBee to Mongock 3(like it is currently, won't bee improved, unless something really wrong)

> From Mongock 4 to Mongock 3:

It will required an easy manual step, which will be provided in the documentation, but will still be guaranteed


> From Mongock(any version) to Mongobee

We won't make any effort in this direction


If I am not wrong, from you comment, this will be enough for you :)

Although we're still in alpha, I'll keep this issue open, so I can keep you updated :)

**Comment by dieppa** [comment]
Hello @pkubowicz , just to keep you updated, we'll have a release with this included by Friday

**Comment by dieppa** [comment]
Hello @pkubowicz ,

there is a new release 4.0.8.alpha which provides migration from legacy changeLogs, such as Mongobee's. Please see this [sample project](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-spring-v5/mongock-spring5-springdata3-it)

The class `MongockLegayMigration` is the on in charge to package all the configuration(from properties file)

Also, to migrate from Mongock 4.x to Mongock 3.x, you only need to run a MongoDB command which is in the readme file of the sample project:
```javascript 1.8
db.mongockChangeLog.remove({$or:[{"state":"FAILED"}, {"state": "IGNORED"}]})
```

Anything else you need, let me know
