### ISSUE TITLE
v3.3.2 and v4.0.x - Question: Possible to create collections mongockChangeLog and mongockLock without indexes?

### ISSUE THREAD

**Issue by janweinschenker** [cloudyrock/mongock#181]
Mongock creates these two collections with indexes ("executionId_1_author_1_changeId_1" and "key_1").

Is it possible to disable the automatic creation of these indexes, e.g. with a configuration property "create-mongock-indexes: false"?

Background to this question:

We are working on a MongoDB server where indexes must be created by other means than by the applications themselves.

**Comment by dieppa** [comment]
provided in version 4.0.7.alpha

**Comment by leonelsanchesdasilva** [comment]
@dieppa Can you please provide an example about how to configure this?

**Comment by dieppa** [comment]
Hello @leonelsanchesdasilva , 
there is no example for that, but it's in the [documentation](https://www.mongock.io/further-configuration#index-creation).

Please, let me know if it's enough with that or we need to provide a proper example.

Cheers

**Comment by leonelsanchesdasilva** [comment]
@dieppa We are currently trying to deploy the application with CosmosDB, which doesn't allow indexes to be created, apparently. Will let you know if this worked.

**Comment by dieppa** [comment]
mmmm, that's a problem as Mongock needs those indexed to be created. The `index-creation=false` solution requires the indexes to be created manually, instead of y Mongock itself, but still the need to be there. I am pretty sure it won't work
