### ISSUE TITLE
mongock-spring-v5 missing SpringMongock bean

### ISSUE THREAD

**Issue by marceloeliseufountainledge** [cloudyrock/mongock#186]
I tried to use mongock-spring-v5 from maven, but it's missing the SpringMongock bean class.

**Comment by dieppa** [comment]
Hello @marceloeliseufountainledge,

in the new 4.x version ,there is no SpringMongock or SpringBootMongock classes. They have been renamed to MongockApplicationRunner and MongockInitializingBeanRunner.

Notice that you don't even care. Just providing `@EnableMongock` annotation to the springboot application and the scan package in the properties, you are fine.

Please take a look to [this example](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-spring-v5/mongock-spring5-springdata3-it)

**Comment by marceloeliseufountainledge** [comment]
Thanks @dieppa ! 
Now the application finished the start after I added mongodb-springdata-v3-driver. 
I'm using mongo Atlas MongoDB 4.2 on cloud,  is it supported (mongo v4 driver) ? 

Also @ChangeLog is not executing, I can see that was created collection mongockChangeLog and mongockLock but there are both empty.

tks !

**Comment by marceloeliseufountainledge** [comment]
No issue so far, it's working  using mongodb-driver-sync-4.0.3 as part of spring-boot-starter-data-mongodb.

Yes, it is a question, because I had to included this dependency:

		<dependency>
		    <groupId>com.github.cloudyrock.mongock</groupId>
		    <artifactId>mongodb-springdata-v3-driver</artifactId>
		    <version>4.0.6.alpha</version>
		</dependency>

**Comment by dieppa** [comment]
Yeah, as per the example, you need to add to your pom:

1. Dependency management bom

```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.0.7.alpha</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

2. Mongock runner

```xml
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
        </dependency>
```

3. Mongock Driver

```xml
     <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
        </dependency>
```

Springdata 3 driver uses mongodb sync 4 driver and Spring-data v3, however they are excluded to avoid transitive dependency issues.

You can see the [mongock-bom](https://github.com/cloudyrock/mongock/blob/master/mongock-bom/pom.xml#L65)

**Comment by marceloeliseufountainledge** [comment]
ok, great! tks a lot !
