### ISSUE TITLE
Spring Boot Mongo Template setup

### ISSUE THREAD

**Issue by mkulle** [cloudyrock/mongock#188]
Hi,
I'm using SpringBoot 2.2.2. I found MongoCK 3.0.3.BETA available only.
I'm trying to switch from MongoBee.
During the test I tried following scenario:
`    @ChangeSet(order = "001", id = "V1.0_00__insert_some_seq", author = "me")
    public void insertSomeSeq(MongoTemplate template)
    {
        Seq seq = new Seq();
        seq.setName("some");
        seq.setLastNo(0L);
        template.insert(seq);
    }
`
There were two issues and both are tight to the same problem. Fields in DB don't follow naming strategy from application.properties, and I'm getting the warning with autoIndexCreation which I solved before.

The issue is that provided MongoTemplate isn't properly setup. I tried a few workarounds and none of those worked. Is there a way how to set up a Mongo Mapping Context correctly?

**Comment by dieppa** [comment]
Hello,

you should use version 3.3.2 and instead MongoTemplate, you should use MongockTemplate. It's exactly the same API(it's just a wrapper/decorator), so you won't miss anything.

Please try this and let me know how it goes :)

On the other hand, we are working on version 4, for which we made some released already. Actually we are working on Mongobee migration, so the next release(this week) will contain this feature.

**Comment by mkulle** [comment]
Thanks for your quick response. I'll give it a shot. However, I've pushed away from this conversion now. I'll let you know as soon as I get back. Thank you.

**Comment by dieppa** [comment]
Hello @mkulle ,
did it work?
