### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mongodb/core/index/IndexOperationsProvider

### ISSUE THREAD

**Issue by arpit038** [cloudyrock/mongock#190]
Hi,
We have migrated our database from MongoDB 3.6 to 4.2. We were using mongobee in our spring boot (v1.5.9.RELEASE) app. Now mongobee is not supported with MongoDb 4.2 as defintion of accessing indexes has changed from db.system.indexes to db.system.getIndexes().

I came across this well known alternative, mongock. 

Now I am migrating from mongobee to mongock and facing issue.

The maven build is success. But while running the application through IntelliJ, I am getting following error,

`Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mongodb/core/index/IndexOperationsProvider
`
on following bean creation,

```
@Bean
  public SpringBootMongock mongock(MongoTemplate mongoTemplate, ApplicationContext springContext) {
    return new SpringBootMongockBuilder(mongoTemplate, "com.company.app")
        .setApplicationContext(springContext).setLockQuickConfig().build();
  }
```

My POM has this dependency,

```
<dependency>
        <groupId>com.github.cloudyrock.mongock</groupId>
        <artifactId>mongock-spring</artifactId>
        <version>3.3.2</version>
</dependency>
```

**Comment by dieppa** [comment]
Hello @arpit038 ,

for MongoDB 4.x you need to use Mongock 4.0.8.alpha

There isn't official documentation yet, but you can see this [sample project](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-spring-v5/mongock-spring5-springdata3-it)

Please notice that although it should work(if you use the mongobee's changeLog collection name)in the next release will provide migration from Mongobee.

For more information about feature in version 4, please see our [roadmap](https://github.com/cloudyrock/mongock#roadmap)

Please let us know if you have any other issue :)

**Comment by arpit038** [comment]
Not able to resolve dependency when using mongock 4.0.8.alpha. Can you share the maven dependency?

**Comment by dieppa** [comment]
If you see the sample I mentioned in the previous comment, you can see you need to import the bom with:

```xml
 <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.0.6.alpha</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

And both Mongock Dependencies, for runner and driver
```xml
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
        </dependency>


        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
        </dependency>
```

**Comment by arpit038** [comment]
With the above dependencies, 
I am not able to create the following bean now,
```
@Bean
  public SpringBootMongock mongock(MongoTemplate mongoTemplate, ApplicationContext springContext) {
    return new SpringBootMongockBuilder(mongoTemplate, "com.company.app")
        .setApplicationContext(springContext).setLockQuickConfig().build();
  }
```

**Comment by dieppa** [comment]
The new approach is by using @EnableMongock in the SpringBootApplication.

Then everything is set in the properties file.Please see the sample project ;)

**Comment by dieppa** [comment]
Important. If you are planning to use MongoTemplate, please use MongockTemplate instead. It's exactly the same API, you won't miss anything.

Thanks

**Comment by arpit038** [comment]
Is there any constraint on using MongockTemplate?
Will it be okay if we continue with MongoTemplate?

**Comment by arpit038** [comment]
@dieppa 
I am getting the following exception while running the app, even I have imported mongock driver as mentioned in sample project pom.xml

```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockApplicationRunner' defined in com.github.cloudyrock.spring.v5.MongockContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner]: Factory method 'mongockApplicationRunner' threw exception; nested exception is io.changock.migration.api.exception.ChangockException: 

MONGOCK DRIVER HAS NOT BEEN IMPORTED
====================================
	SOLUTION: You need to import one of these artifacts
	- 'mongodb-springdata-v3-driver' for springdata 3
	- 'mongodb-springdata-v2-driver' for springdata 2
```

**Comment by dieppa** [comment]
Hi @arpit038 ,

**Will it be okay if we continue with MongoTemplate?** - No, you cannot use MongoTemplate, as there is no reason for you to do it. MongockTemplate is just a wrapper/decorator.

Regarding your exception, I don't have enough information to help you. 
Can you share your pom.xml and your properties file(the part related to Mongock)?

**Comment by dieppa** [comment]
Hi @arpit038 ,

please let us know how it went. Otherwise this issue will be closed in the next 24-48 hours
