### ISSUE TITLE
How to configure a bean for mongock?

### ISSUE THREAD

**Issue by tigermarques** [cloudyrock/mongock#195]
Hi,

I'm new to Mongock (even though I've used Mongobee in the past). I'm using the 4.0.8.alpha version. However, I have a question about how to setup the Bean when integrating the app with Spring.

In the README, you have the following code:
```
@Bean
public SpringMongock springMongock(MongoTemplate mongoTemplate, Environment springEnvironment) {
  return new SpringMongockBuilder(mongoTemplate, "changeLogScanPackage")
        .setSpringEnvironment(springEnvironment)
      .setLockQuickConfig() OR .setLockConfig(3, 4, 3) 
       ...other setters
      .build();
}
```

However, I've added the `mongock-spring-v5` dependency to my project, and that class does not exist for me. Do I have to import anything else? Did this change in v5?

Thank you very much in advance!

**Comment by dieppa** [comment]
Hello, 

so sorry, but we are working to have the  documentation for the version 4.X available as soon as possible. We expect to have the basic for you to start at the end of the week.

Meanwhile, you should know that, although you can still use the builder(no that one exactly), we have provided a much better approach based on annotation. You basically need to annotate your SpringBootApplication class with @EnableMongock and provide everything in the property files.

Please take a look to [this example](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-spring-v5/mongock-spring5-springdata3-it).

Anyway I provide the basic steps you should follow:
1.  Add Mongock bom to your pom:
```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.0.8.alpha</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

2. provide Mongock runner and Mongock Driver dependencies
```xml

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
        </dependency>
```

3. As these Mongock dependencies don't bring MongoDB driver nor Spring data dependencies, to avoid transient dependencies, you need to import them

4. Add you changeLog package path to your property file
```yaml
spring:
  mongock:
    change-logs-scan-package:
      - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.initializer
```

5. Annotate your SpringBootApplication with @EnableMongock
```java
@EnableMongock
@SpringBootApplication
public class App {

  public static void main(String[] args) {
    new SpringApplicationBuilder().sources(App.class).run(args);
  }
}
```


With that you should be fine. Please notice that, if you want to use MongoTemplate in your changeLogs, you should use MongockTemplate instead. It's just a wrapper/decorator, so you won't notice any difference.

However, you can use spring data repositories if you want. Actually you can use any custom bean as long as it's an interface.

I hope it's helpful. If you need anything else, please let us know.

**Comment by tigermarques** [comment]
Thank you very much for your answer. It helps a lot.

Is there any way that I can control the actual bean created by Mongock?
My use case is quite simple. I need to change the structure of a collection, which involved changing an index. Therefore, I will create a changelog to do this. It will remove the old index, and transform the documents in the collection for the new structure.
However, I want to create new indexes that depend on the new structure of the collections. Since some of the index logic might be complex, I have a separate configuration class to do this, that looks like this:

```
@Configuration
public class IndexConfig {
    @Autowired
    public IndexConfig(MongoTemplate mongoTemplate) {
        // Any Index logic should go here
    }
}
```

My requirement is that this class is only ran after the migration happened. If that is not the case, then the index creation will fail since the document structure is not valid. If I could control the bean, then I could add here a `@DependsOn(...)`. Do you have any other way of achieving the same result?

Thank you!

**Comment by dieppa** [comment]
OK, if you need more control. You can either  opt for the standalone runner, which is spring independent or not annotate you class with @EnableMongock and use the builder manually, like this:
```java
@Bean
public MongockSpring5.MongockApplicationRunner mongockApplicationRunner(ApplicationContext springContext, MongoTemplate mongoTemplate) {
    return MongockSpring5.builder()
        .setDriver(new SpringDataMongo3Driver(mongoTemplate))
        .addChangeLogsScanPackages("your changeLog package path")        
        .setSpringContext(springContext)
        // any extra configuration you need
        .buildApplicationRunner();
  }
```

Or this if you require a Spring InitializingBean instead of a Spring ApplicationRunner
```java
@Bean
public MongockSpring5.MongockInitializingBeanRunner mongockInitializingBeanRunner(ApplicationContext springContext, MongoTemplate mongoTemplate) {
    return MongockSpring5.builder()
        .setDriver(new SpringDataMongo3Driver(mongoTemplate))
        .addChangeLogsScanPackages("your changeLog package path")        
        .setSpringContext(springContext)
        // any extra configuration you need
        .buildInitializingBeanRunner();
  }
```

**Comment by tigermarques** [comment]
That works perfectly. Thank you very much!

**Comment by anandjaisy** [comment]
> OK, if you need more control. You can remove the annotation @EnableMongock in your SpringBootApplication class and use the builder manually, like this:
> 
> ```java
> @Bean
> public MongockSpring5.MongockApplicationRunner mongockApplicationRunner(ApplicationContext springContext, MongoTemplate mongoTemplate) {
>     return MongockSpring5.builder()
>         .setDriver(new SpringDataMongo3Driver(mongoTemplate))
>         .addChangeLogsScanPackages("your changeLog package path")        
>         .setSpringContext(springContext)
>         // any extra configuration you need
>         .buildApplicationRunner();
>   }
> ```
> 
> Or this if you require a Spring InitializingBean instead of a Spring ApplicationRunner
> 
> ```java
> @Bean
> public MongockSpring5.MongockInitializingBeanRunner mongockInitializingBeanRunner(ApplicationContext springContext, MongoTemplate mongoTemplate) {
>     return MongockSpring5.builder()
>         .setDriver(new SpringDataMongo3Driver(mongoTemplate))
>         .addChangeLogsScanPackages("your changeLog package path")        
>         .setSpringContext(springContext)
>         // any extra configuration you need
>         .buildInitializingBeanRunner();
>   }
> ```
> 
> I hope this works ;)

Hi

Can you please post the code for Standalone without spring boot application

**Comment by dieppa** [comment]
Hello @anandjaisy, please follow these steps:

1) you need to  remove the mongock-spring-v5 dependency from your pom and add:
```xml
<dependency>
    <groupId>com.github.cloudyrock.mongock</groupId>
    <artifactId>>mongock-standalone</artifactId>
</dependency>
```

2) Then use the Mongock Driver you required(for Java MongoDB driver version 3 or 4):
```xml
<dependency>
    <groupId>com.github.cloudyrock.mongock</groupId>
    <artifactId>mongodb-sync-v4-driver</artifactId>
</dependency>

or 

<dependency>
    <groupId>com.github.cloudyrock.mongock</groupId>
    <artifactId>mongodb-v3-driver</artifactId>
</dependency>
```

3) Import your Java MongoDB driver:

```xml
<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongodb-driver-sync</artifactId>
    <version>${mongodb.driver-sync.version}</version>
</dependency>

or

<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongo-java-driver</artifactId>
    <version>${mongodb.java-driver}</version>
</dependency>
```

4) Build Mongock with builder approach
```java
MongockStandalone.builder()
        .setDriver(MongoSync4Driver.withDefaultLock(mongoCient.getDatabase("your_db"))
        .addChangeLogsScanPackage("your_changeLog_package_path")
        .buildRunner()
```

**Comment by anandjaisy** [comment]
For the changeset how we are making the dependency for MongockTemplate ?

**Comment by dieppa** [comment]
MongockTemplate is just a wrapper for MongoTemplate, so if you are not using Spring Data, you cannot use MongockTemplate. You need to stick to what Java MongoDB driver offers ;)

**Comment by anandjaisy** [comment]
I have something like this?

```
public class main {
    public static void main(String[] args) {
        MongockStandalone();
    }

    private static void MongockStandalone(){
        MongoClient mongoClient = MongoClients.create("mongodb://127.0.1:27017/FeteBird-Product");
        MongockStandalone.builder()
                .setDriver(MongoSync4Driver.withDefaultLock(mongoClient.getDatabase("FeteBird-Product")))
                        .addChangeLogsScanPackage("migration")
                        .buildRunner().execute();
    }
}
```

**And Changeset**

```
@ChangeLog(order = "001")
public class DbChangeLog001 {
    @ChangeSet(order = "001", id = "seedProduct", author = "San")
    public void seedProduct(MongoTemplate mongoTemplate) {
        mongoTemplate.insert(new Product());
    }
}
```
Dependencies

```
implementation 'org.springframework.boot:spring-boot-starter-data-mongodb:2.3.1.RELEASE'
    implementation 'com.github.cloudyrock.mongock:mongock-standalone:4.1.2.BETA'
    implementation "com.github.cloudyrock.mongock:mongodb-sync-v4-driver:4.1.2.BETA"
    implementation 'org.mongodb:mongodb-driver-sync:4.1.0-rc0'
```

The changeset is not executed, can you please help me with this.

**Comment by dieppa** [comment]
As said in my previous comment, you cannot use MongoTemplate unless you use Spring Data, which I don't think you are
**Notice, in any case you should be using MongockTemplate, not MongoTemplate**.

You changeSet should be something like:
```java
@ChangeLog(order = "001")
public class DbChangeLog001 {
    @ChangeSet(order = "001", id = "seedProduct", author = "San")
    public void seedProduct(MongoDatabase mongoDatabase) {
       mongoDatabase.getCollection("your_collection").insertOne(mew Document());
    }
}
```


Also notice you don't need to specify the database in your MongoClient.create. It's enough with
```java
 MongoClient mongoClient = MongoClients.create("mongodb://127.0.1:27017");
```

and then you pass to Mongock the database.

**Comment by anandjaisy** [comment]
Still not working for me. Same issue

**Comment by anandjaisy** [comment]
Thank you. It worked

**Comment by anandjaisy** [comment]
One more question, How do you pass MongoTemplate  or MongockTemplate in the MongockStandalone.builder() if I will use SpringData using mongodb-springdata-v3-driver
