### ISSUE TITLE
Doesn't start migration task

### ISSUE THREAD

**Issue by webster91** [cloudyrock/mongock#198]
Good day.
The migration task does not start because the shell task has a higher order.

My deps

        <dependency>
            <groupId>org.springframework.shell</groupId>
            <artifactId>spring-shell-starter</artifactId>
            <version>2.0.1.RELEASE</version>
        </dependency>

and

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring</artifactId>
            <version>3.2.5</version>
        </dependency>

 My config

    @Bean
    public SpringBootMongock mongock(MongoTemplate mongoTemplate, ApplicationContext springContext) {
        return new SpringBootMongockBuilder(mongoTemplate, DatabaseChangelog.class.getPackage().getName())
                .setApplicationContext(springContext)
                .setLockQuickConfig()
                .build();
    }

Spring-shell  has ApplicationRunner with ordrer @Order(-100) and SpringBootMongock without order.

**Comment by dieppa** [comment]
Hello @webster91,

do you get any error/warning message in your log? I don't  have enough information, but technically you shouldn't have any problem running more than one ApplicationRunner.

To be honest I haven't come up against this issue before. I'm wondering if this could be easily fixed by adding @Order to your SpringBootMongock bean

**Comment by webster91** [comment]
Errors do not occur. I tried to set a higher priority, did not work (

**Comment by dieppa** [comment]
This seems an issue or misconfiguration related to Spring. I suggest to put a break point to ensure your Mongock bean is been setting up. And research about it, but "build" just return an ApplicationRunner, then it delegate to Spring the "running" task.

**Comment by webster91** [comment]
I checked the Mongock bean starts, but SpringBootMongock doesn't start.
ScriptShellApplicationRunner interrupts it with @Order (-100).
If I could extends from SpringBootMongock and set order or somehow overturn him order.

**Comment by webster91** [comment]
If I use SpringMongock everything works fine, but there is no way to inject dependencies


    public SpringMongock mongock2() {
        return new SpringMongockBuilder( mongoTemplate, "ru.otus.valeev.config.migration")
                .setSpringEnvironment(springEnvironmen)
                .setLockQuickConfig()
                .build();
    }

**Comment by dieppa** [comment]
what does stop you from doing this?:

```java
public class SpringMongockOrderedRunnerWrapper implements ApplicationRunner, Ordered {

  private final SpringBootMongock mongockInstance;

  public SpringMongockOrderedRunnerWrapper(SpringBootMongock mongockInstance) {
    this.mongockInstance = mongockInstance;
  }
  
  @Override
  public int getOrder() {
    return Ordered.HIGHEST_PRECEDENCE;
  }

  @Override
  public void run(ApplicationArguments args) {
    mongockInstance.run(args);
  }
}
```

and then in your Spring context class, defining this bean:
```java
@Bean
public SpringMongockOrderedRunnerWrapper mongockOrdered(SpringBootMongock mongockRunner) {
 return new SpringMongockOrderedRunnerWrapper(mongockRunner);
}
```

**Comment by webster91** [comment]
Thank you so much. it works.
