### ISSUE TITLE
Need help with mongock-spring-5

### ISSUE THREAD

**Issue by mvcaraiman** [cloudyrock/mongock#211]
I'm trying to use Mongock Spring5 version 4.1.2.BETA and I'm not able to find a way to create an instance of MongockSpring5.
The link on the main page "Last news" section "this example" gives an 404. Can anyone  help me with this ?

**Comment by dieppa** [comment]
Sorry, we haven't released the official documentation for version 4.x. We expect to have it ready next week. Meanwhile, take a look to [this issue](https://github.com/cloudyrock/mongock/issues/195).

Let me know how it goes. Thanks

**Comment by dieppa** [comment]
although this [sample project](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-4/mongock-spring-v5/mongock-spring5-springdata3-it)

**Comment by dieppa** [comment]
Please let me know how it goes, otherwise I will close this issue in 24 hours ;)

**Comment by mvcaraiman** [comment]
Hi @dieppa , 
 thank for your quick answer. I saw the code sample is for SpringBoot projects and it returns an MongockInitializingBeanRunner or an MongockApplicationRunner  , how do I get the equivalent of  SpringMongockBuilder for a Spring , non-SpringBoot project ?

**Comment by dieppa** [comment]
Hello @mvcaraiman ,

please see [this issue](https://github.com/cloudyrock/mongock/issues/195) at the bottom I explain how to execute a MongockStandalone runner ;)

**Comment by dieppa** [comment]
@mvcaraiman please notice that as you're not using Spring data, you are not able to use MongoTemplate. It's explained there too

**Comment by dieppa** [comment]
Please let me know if this is fixed.

Thanks

**Comment by mvcaraiman** [comment]
Hi, @dieppa, 
 My setup is this : I use Spring Data, but not with Spring Boot and  I have a bean of  type org.springframework.data.mongodb.core.MongoTemplate.  Finally I was able to make it work with this : 
1. I used mongodb-v3-driver + mongock-standalone  4.1.2.BETA 
2. code : 
MongockStandalone.builder().setDriver(MongoCore3Driver.withDefaultLock(mongoTemplate.getDb()))
                .addChangeLogsScanPackage(MongockChangeSets.class.getPackageName())
                .buildRunner().execute();

It's confusing that the class MongoCore3Driver.withDefaultLock from mongodb-v3-driver accepts a parameter of type org.springframework.data.mongodb.core.MongoTemplate which comes from spring-data  ( I was not able to make it work with mongodb-springdata-v3-driver, that was giving me errors like : 
Caused by: java.lang.NoSuchMethodError: com.mongodb.client.MongoCollection.insertOne(Ljava/lang/Object;)Lcom/mongodb/client/result/InsertOneResult; at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.save(MongoSync4ChangeEntryRepository.java:55) ~[mongodb-sync-v4-driver-4.1.2.BETA.jar:?]

Cheers, 
 Marian.

**Comment by dieppa** [comment]
Hi @mvcaraiman ,

that error it's because mongodb-springdata-v3-driver, uses `org.springframework.data:spring-data-mongodb:3.XX`, which underneath uses `org.mongodb:mongodb-driver-sync:4.02` (brought it by the transitive mongock dependency `com.github.cloudyrock.mongock:mongodb-sync-v4-driver`, but it seems you are using, directly or underectly, MongoDB Java Driver 3.x.

### SOLUTION 

In summary, it should work what you tried, but using **mongodb-springdata-v2-driver** instead mongodb-springdata-v3-driver.

Please have a try and let me know

**Comment by dieppa** [comment]
has this been resolved?

**Comment by mvcaraiman** [comment]
Yes, it was solved using mongodb-sync-v4-driver + MongoSync4Driver
Thank you for your support
