### ISSUE TITLE
Support for module path in Java module system

### ISSUE THREAD

**Issue by namannigam** [cloudyrock/mongock#212]
Referring to the Q&A on StackOverflow - [How to fix the issue with Java 9 Modularity after adding a dependency on `mongock`?](https://stackoverflow.com/questions/62933733)

Seems like the upgraded versions in the `4.x.x` somehow manage to get away with this using different dependency and improved package structures. But is there a plan around explicitly introducing `Automatic-Module-Name` under the `META-INF/MANIFEST.MF` of the library to start off with and then maybe modularise it later?

**Comment by dieppa** [comment]
Hello @namannigam , 

we have plans to make some adjustment to adapt to new versions of Java, but we have some other priorities first. This might be coming after transactions and some other cool features we are working on.

Thanks
