### ISSUE TITLE
MongockCoreContextSelector - invalid condition?

### ISSUE THREAD

**Issue by jfenuk** [cloudyrock/mongock#214]
I've just briefly reviewed source code and in my opinion, found  an issue in `MongockCoreContextSelector`:

```
Class.forName("com.github.cloudyrock.mongock.driver.mongodb.springdata.v2.SpringDataMongo3Driver");
```
believe, that the right class name is `com.github.cloudyrock.mongock.driver.mongodb.springdata.v2.SpringDataMongo2Driver` not `com.github.cloudyrock.mongock.driver.mongodb.springdata.v2.SpringDataMongo3Driver`.

Could you please take a look?

**Comment by dieppa** [comment]
Yes, you are right. Tests didn't spot that because integration tests for the spring configuration are only for Spring data v3.

It will be fixed tomorrow morning(UK time)

Thanks

**Comment by jfenuk** [comment]
@dieppa , any updates?

**Comment by dieppa** [comment]
@jfenuk , sorry, we have a crazy morning. We'll be releasing a bugfix during the day. If you prefer, as it's pretty easy, feel free to create a PR yourself, we can perform our tests and checks and validate it

**Comment by dieppa** [comment]
version 4.1.3.BETA released with bug fixed
