### ISSUE TITLE
Why is a subclass of ChangeEntry used for non-legacy migrations?

### ISSUE THREAD

**Issue by mjustin** [cloudyrock/mongock#226]
Very, very minor thing I noticed when testing the 4.1.8 version of Mongock in Spring Boot with Spring Data Mongo 3.  Since this is using `MongoTemplate` to save the `ChangeEntry`, a "_class" property is added by default by Spring Data to all documents stored.  I noticed that the legacy migrations inserted a direct instance of `ChangeEntry`, but the regular migrations inserted an anonymous subclass of `ChangeEntry` (`"io.changock.driver.api.entry.ChangeEntry"` vs. `"io.changock.driver.api.entry.ChangeEntry$1"` in the generated `"_class"` field).  The resulting behavior is certainly correct, but looking at the code, I don't see any obvious reason the non-legacy `ChangeEntry`s would need to be an anonymous subclass, rather than a regular instance.

The anonymous subclass is created in [`ChangeEntry.createInstance()`](https://github.com/cloudyrock/changock/blob/beb30da345a0b4266494ca3d2015698bc8a25143/changock-driver/changock-driver-api/src/main/java/io/changock/driver/api/entry/ChangeEntry.java#L46) (in the Changock project), whereas the direct instance is created in [`MongockSync4LegacyMigrationChangeLog.getOriginalMigrationAsChangeEntryList()`](https://github.com/cloudyrock/mongock/blob/1718882e0c58cd45c368fca3aa7d3383a76c4708/drivers/mongodb-sync-v4-driver/src/main/java/com/github/cloudyrock/mongock/driver/mongodb/sync/v4/changelogs/MongockSync4LegacyMigrationChangeLog.java#L81).  I guess ultimately, wouldn't it be slightly better it were changed from:

```java
    return new ChangeEntry(
        executionId,
        changeSet.getId(),
        changeSet.getAuthor(),
        new Date(),
        state,
        changeSet.getMethod().getDeclaringClass().getName(),
        changeSet.getMethod().getName(),
        executionMillis,
        metadata) {
    };
```

to:

```java
    return new ChangeEntry(
        executionId,
        changeSet.getId(),
        changeSet.getAuthor(),
        new Date(),
        state,
        changeSet.getMethod().getDeclaringClass().getName(),
        changeSet.getMethod().getName(),
        executionMillis,
        metadata);
```

That all said, this is clearly a super minor thing, and doesn't result in any incorrect behavior (though it does look a little bit weird in the `mongockChangeLog` Mongo collection).

### application.yml
```
mongock:
  change-logs-scan-package: com.example.my.migrations
  legacy-migration:
    collection-name: dbchangelog
```

### mongockChangeLog

```
> db.mongockChangeLog.find().pretty()
{
	"_id" : ObjectId("5f1f46a2bbd15512ac8ec88f"),
	"executionId" : "legacy_migration-2020-07-27T17:26:58.302845-300",
	"changeId" : "legacyChange",
	"author" : "JDoe",
	"timestamp" : ISODate("2020-07-27T20:02:25.453Z"),
	"state" : "EXECUTED",
	"changeLogClass" : "com.example.my.migrations.V20200515170000_LegacyChange",
	"changeSetMethod" : "doLegacyChange",
	"metadata" : {
		"migration-type" : "legacy"
	},
	"executionMillis" : NumberLong(-1),
	"_class" : "io.changock.driver.api.entry.ChangeEntry"
}
{
	"_id" : ObjectId("5f1f46a2bbd15512ac8ec890"),
	"executionId" : "2020-07-27T17:26:58.289679-834",
	"changeId" : "mongock-legacy-migration",
	"author" : "mongock",
	"timestamp" : ISODate("2020-07-27T21:26:58.366Z"),
	"state" : "EXECUTED",
	"changeLogClass" : "com.github.cloudyrock.mongock.driver.mongodb.sync.v4.changelogs.MongockSync4LegacyMigrationChangeLog",
	"changeSetMethod" : "mongockSpringLegacyMigration",
	"executionMillis" : NumberLong(70),
	"_class" : "io.changock.driver.api.entry.ChangeEntry$1"
}
{
	"_id" : ObjectId("5f1f46a2bbd15512ac8ec891"),
	"executionId" : "2020-07-27T17:26:58.289679-834",
	"changeId" : "mongockChange",
	"author" : "JDoe",
	"timestamp" : ISODate("2020-07-27T21:26:58.403Z"),
	"state" : "EXECUTED",
	"changeLogClass" : "com.example.my.migrations.V20200617120000_MongockChange",
	"changeSetMethod" : "doMongockChange",
	"executionMillis" : NumberLong(14),
	"_class" : "io.changock.driver.api.entry.ChangeEntry$1"
}
```

**Comment by dieppa** [comment]
Hello @mjustin, I don't fully understand your question. First think confuses me is that you mention "anonymous class" but unless I miss something, there is no anonymous class anywhere.

Regarding why Spring stores the field class with "$1", I don't really understand. I need to take a look deeply, but as you say that's normally used for anonymous classes.

We'll take a look and tell you something

**Comment by dieppa** [comment]
ooooooh yes, I see it, the brackets! I looked at that piece of code 923923 times I never saw it. Now everything makes sense :D 
No, that totally sneaked in, there is no reason for that. We'll remove it, as you said very minor issue.

Thanks!!

**Comment by dieppa** [comment]
done in changock:1.1.3
