### ISSUE TITLE
Fails to start up with mongo version 4.4.0

### ISSUE THREAD

**Issue by kraii** [cloudyrock/mongock#234]
Using version 4.1.8 against mongo 4.4.0

`com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase#isUniqueIndex` always returns false, as the `ns` field is not present in the documents given from `collection.listIndexes`

This means that `io.changock.migration.api.exception.ChangockException: Max tries 3 index  creation` is thrown.

All I could see in the mongo documentation about this change is that the [getIndexes](https://docs.mongodb.com/v4.2/reference/method/db.collection.getIndexes/) page  says:

> Starting in MongoDB 4.4, db.collection.getIndexes() no longer includes the ns field.

**Comment by dieppa** [comment]
hi. yeah, that ns check should be removed as it doesn't make sense anymore.
thanks

**Comment by dieppa** [comment]
Hi @kraii, it's fixed in 4.1.14. 

Thanks
