### ISSUE TITLE
CustomConversions in migration 

### ISSUE THREAD

**Issue by savvadem** [cloudyrock/mongock#238]
Hello
we have custom conversion for enums, to store values as integers.

Here is sample of migration we are using to create parital index

```
    @ChangeSet(order = "008", id = "addProcessingPartialIndex", author = "savva")
    public void addProcessingPartialIndex(MongoTemplate template) {

        IndexOperations indexOperations = template.indexOps(Operation.class);
        String indexes = "{'status':1, 'type':1, 'updatedAt': -1}";
        Document parse = Document.parse(indexes);
        CompoundIndexDefinition indexDefinition = new CompoundIndexDefinition(parse);
        indexDefinition.background().partial(PartialIndexFilter.of(
                Criteria.where("processingStatus")
                        .is(template.getConverter().convertToMongoType(Status.PROCESSING))
                        .and("operationType")
                        .is(template.getConverter().convertToMongoType(Type.MOVE))));
        indexOperations.ensureIndex(indexDefinition);
    }
```
In mongodb atlas i can see partial index with String values, but i expect to have int values(on different enviroments it should be string or int, for example in dev/qa enviroment we should have String values, and pre-prod/prod env should be int value). 
Looks like Mongock does not use our custom converters, and MongoTemplate injected to migration method above does not have converters.

**Comment by dieppa** [comment]
Hello @savvadem,

what Mongock version are you using? I can see that you use MongoTemplate, instead of MongockTemplate, so it's probably and old one.

I suggest you to upgrade your Mongock version. Please see  the [documentation](https://www.mongock.io/quick-start)

**Comment by savvadem** [comment]
version 3.2.4
Ok i will try tomorrow new version and reply here.

Thanks

**Comment by dieppa** [comment]
cool, let me know how it goes.

**Comment by savvadem** [comment]
Sry for long reply.

I upgraded to 4.1.8 and it works like a charm.
I have one suggestion - could you add scan-package to ```@EnableMongock``` annotation? 
So it would be like this:
```@EnableMongock(package = "com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.initializer")```

**Comment by dieppa** [comment]
Hi @savvadem ,
Good suggestion, thanks!

Did you have change to look at the documentation? What do you think? Is it OK? easy and intuitive or difficult? any suggestion?

Thanks

**Comment by savvadem** [comment]
Well i would say that it was hard to understand(for me) how to configure dependencies.

I think better just to show how to configure the whole thing:
for example this is spring boot 2.2.6 gradle
```
    compile 'com.github.cloudyrock.mongock:mongock-spring-v5:4.1.8' 
    compile 'com.github.cloudyrock.mongock:mongodb-springdata-v2-driver:4.1.8'
```
and e.t.c.

Also i think you need to mention ```@Bean``` annotation in section "Traditional builder approach".

**Comment by dieppa** [comment]
Hi @savvadem ,

1) So you mean that in [quick start](https://www.mongock.io/quick-start) instead of explaining step by step providing the different options in each one, it would be better providing for each option all the steps together, so you just need to almost copy/paste, right? Something like this:

For spring data 3:
```xml
<dependency>
    <groupId>com.github.cloudyrock.mongock</groupId>
    <artifactId>mongock-spring-v5</artifactId>
</dependency>

<dependency>
    <groupId>com.github.cloudyrock.mongock</groupId>
    <artifactId>mongodb-springdata-v3-driver</artifactId>
</dependency>

<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongodb-driver-sync</artifactId>
    <version>${mongodb.driver-sync.version}</version>
</dependency>
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-mongodb</artifactId>
    <version>${mongodb.spring-data.v3.version}</version>
</dependency>
```


2. Yeah, I think that should be more clear too.

**Comment by savvadem** [comment]
1. Yeah i'm about quick start. I think most of users already have mongo in deps list, so  you could hide this instructions somewhere and focus on your deps(mongock-spring-v5 and mongodb-springdata-v3-driver) and how to use them with examples.
