### ISSUE TITLE
Can't disable Mongock in unit tests

### ISSUE THREAD

**Issue by santam85** [cloudyrock/mongock#239]
In Spring Boot unit tests that partially initialise the application context (IE: `@JsonTest`), the Mongock builder tries to instantiate the driver anyway, and you get exceptions because of the missing MongoTemplate:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method mongockConnectionDriver in com.github.cloudyrock.spring.v5.MongockSpringDataV3CoreContext required a bean of type 'org.springframework.data.mongodb.core.MongoTemplate' that could not be found.
```

It would be nice to have a way to completely disable mongock beans instantiation during test execution.

**Comment by dieppa** [comment]
That's a known [bug](https://github.com/cloudyrock/mongock/issues/225) . It will be fixed in the next minor release, which e this week.

**Comment by dieppa** [comment]
I close this issue as [this](https://github.com/cloudyrock/mongock/issues/225) as this is already in place

**Comment by sassrobi** [comment]
Can we reopen this issue, as the original problem still exists? I'm using Mongock 5.1.0 and Spring Boot 2.6.8 . When I write a test with `@JsonTest`, Spring tries to auto-configure Mongock, but fails with `No qualifying bean of type 'io.mongock.driver.api.driver.ConnectionDriver'`.
As a _workaround_ adding `@TestPropertySource(properties = ["mongock.enabled=false"])` fixes the issue (which was the [linked other issue](https://github.com/mongock/mongock/issues/225)), but `@JsonTest` (as well as [other](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.autoconfigured-tests) partial-context tests like `@WebMvcTest`, `@DataJpaTest`, etc) should not load the full context with database and other initializers. Developers should not disable directly anything in these tests.

**Comment by dieppa** [comment]
Hello @sassrobi, I get your point. I can think of multiple ways of approaching this, but to be honest all of them are involves much more work than the benefit the developer gets. Specially having the long list of features we have in our backlog and having a workaround which doesn't feel that bad to me.

However, you are welcome to raise a PR for this. It would be a pleasure to assist you in this and review it 😃

**Comment by sassrobi** [comment]
Thank you for your reply. Sadly, i don't have enough experience for doing this, and I don't have time either  😔
