### ISSUE TITLE
how to pass object from one changeset to another

### ISSUE THREAD

**Issue by BeeTrojan** [cloudyrock/mongock#243]
I wanna pass object from one changeset to another. This is my solution but I don't know if it's correct. 
I will be grateful if you could share your proposition.
````
@ChangeLog(order = "001")
public class DatabaseChangelock {

    private Map<String, ObjectId> myIdMap = new HashMap<>();

    @ChangeSet(order = "001", id = "logs001", author = "Me")
    public void userTest(UserEntityRepo user) {
        UserEntity userEntity = new UserEntity;
        
        userEntity.setName("Mike");
        userEntity.setSurname("Smith");
        
        user.save(userEntity);
        myIdMap.put("test",userEntity.getId());

    }
    @ChangeSet(order = "002", id = "logs002", author = "Me")
    public void factoryTest(FactoryEntityRepo factory) {
        FactoryEntity factoryEntity = new FactoryEntity;
        
        factoryEntity.setName("BigCompany");
        factoryEntity.setBossId(myIdMap.get("test"));
        factory.save(factoryEntity);
    }
}

**Comment by dieppa** [comment]
Hi @BeeTrojan,

I don't really recommend stateful chanteLogs. However, if you really need so, the way you are doing would wok.
However, as this seems to be part of the same operation, I'd do it in the same changeSet.

**Comment by dieppa** [comment]
Hi @BeeTrojan , did you resolved your issue?

**Comment by BeeTrojan** [comment]
Hi @dieppa 

I'm trying to find a solution, but it isn't easy. My idea turned out to be bad. :( I tried to do it in the same changeSet, but when 
subsequent operations in changeset didn't work, there was an error with all earlier operations being saved in mongodb. I need something like transaction for changeset.

**Comment by dieppa** [comment]
Hi @BeeTrojan , what do you mean with "transaction for changeset"?

**Comment by BeeTrojan** [comment]
When I made a mistake in one line in my changeset I would like the whole changeset to be complete or not at all. I tried to solve my problem with https://www.mongock.io/transactions#how-to-use-transactions, but i can't add this bean

**Comment by dieppa** [comment]
If you are considering to use transactions, I assume your MongoDB database is 4.0 or higher.

In that case I suggest you to follow the official MongoDB and Spring documentation and then just follow the [Mongock documentation](https://www.mongock.io/transactions#how-to-use-transactions) to tell it to use  transactions.

Please notice that right now, Mongock only supports all-or-nothing transactions, this means that just one transaction is created to the entire migration.

We are working to provide different levels of transactions as well as other mechanisms to help in non-transactional environments.

**Comment by BeeTrojan** [comment]
Thanks for help. I solved my problem :)
