### ISSUE TITLE
Disable index creation

### ISSUE THREAD

**Issue by gsunny488** [cloudyrock/mongock#273]
I would like to disable index creation while running the migration. Would like to have a better understanding for the below queries.
1. What is the impact of disabling the index creation on the migration change logs? 
2. How can I configure to disable the creation of indexes?
3. If at all we need to create necessary indexes how can we achieve it as a separate script rather than auto creation of indexes.

@dieppa Any help here is appreciated.

**Comment by dieppa** [comment]
Hello @gsunny488 ,

1. There is no impact, as long as you ensure the required indexes at created before Mongock starts
2. Please see the [documentation](https://www.mongock.io/further-configuration#index-creation)
3. If you are asking which indexes need to be created, you have it in the documentation link from the previous point.

I hope that resolves your questions :)

**Comment by gsunny488** [comment]
@dieppa - Is this piece of logic correct 
  protected boolean isUniqueIndex(Document index) {
    return fullCollectionName.equals(index.getString("ns")) //changes namespace: [database].[collection]
        && **index.getBoolean("unique", false);// checks it'unique**
  }

The highlighted condition will be true always right? Also how do add "ns"(namespace) while index creation.

**Comment by dieppa** [comment]
Hello again,

that doesn't matter. The indexes showed in the documentation are just an example of what you should see. I didn't want to provide the code to create, as that might change with MongoDb versions, but the result instead, which is what is important. You only need to create the indexes with a command similar to the following:

```javascript
db.mongockChangeLog.createIndex( { executionId: 1, author: 1, changeId: 1 }, { unique: true } )
```

Please, note that although I am confident the previos command will work,  I haven't checked it. So make sure it produce the expected result ;)

Regards

**Comment by gsunny488** [comment]
Yes I used the same to create the index but the namespace is not added in the index details because of which the migration is aborted. Any ideas?

**Comment by dieppa** [comment]
Which Mongock version are you using? I am pretty sure we removed that.

**Comment by dieppa** [comment]
Hello, is this issue still relevant?
