### ISSUE TITLE
Question. Run migration manually.

### ISSUE THREAD

**Issue by savvadem** [cloudyrock/mongock#288]
Hello
Is there a way to run migration manually?

I'm writing console migration application for my admin team, so they can run long-time migration manually via some kind of command. 

Use case is following:
* long running migration, handle few million records. 
* there should be start/stop mechanism 
* start/stop via command from admin

For now, as far as i can tell, migration will start automatically for specified package.

**Comment by dieppa** [comment]
Hello @savvadem ,

sorry but Mongock is not intended for this can of use. Mongock is a migration tool for java application. Mainly to help you to keep your code and database synchronised.

 If I understand well, you are trying to develop a migration tool for your team admin. Then Mongock it's not the best tool, actually don't think It will help you at all.

**Comment by savvadem** [comment]
Thanks for reply.

So how you keep "code and database synchronised." when you need to update all documents in collection?
For example you have 4 fields of type T, and in next release you want move these fields to List<T>?
The goal is to prepare migration, but start it manually.

**Comment by dieppa** [comment]
The goal is basically make sure that when your code runs, it will be synchronised with the database schema. So you don't have un structure in your database that is not synchronised with your code at runtime. 

That gets even more complex when running different instances of the same service, if you require high availability, when you have a limited starting time restricted by your infrastructure(Kubernetes or whatever), etc. 

If you you just need to migrate some data or build a migration tool, Mongock is not what you need ;)
