### ISSUE TITLE
Majority read/write concern is hard-coded in some places and non-configurable.

### ISSUE THREAD

**Issue by scottfrazer** [cloudyrock/mongock#294]
**Describe the bug** 

In this commit: https://github.com/cloudyrock/mongock/commit/3f4fb2e1816196fafd80563b7ea28984c2d661ff

Majority read and write concern is being hard-coded.  It makes sense as a default option, but for some pre-3.6 Mongo instances, majority read concern is not enabled by default (or perhaps it could be turned off on purpose)

Is it okay to allow the default to be overridden?

**To Reproduce**

Run pre-3.6 mongo without `--enableMajorityReadConcern`.  Migrations cannot be run in this case.

**Expected behavior**

Configurable read/write concern

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by dieppa** [comment]
Good point, thanks. We'll improve this and will notify you

**Comment by abobwhite** [comment]
Just encountered this trying to use 4.3.2 when using https://github.com/bwaldvogel/mongo-java-server which is used for integration tests and some local development instead of a real mongo instance. Would love to have this configurable!

**Comment by dieppa** [comment]
Hello @abobwhite , can you explain a bit more? I don't fully understand your point. I see that can be a useful tool for integration tests, but I am not sure why is related to this issue. Thanks!

**Comment by abobwhite** [comment]
Sure @dieppa. When running a local config using embedded mongo or in our integration tests, the spring boot application full initializes and executes the mongock changelogs. This is a good way to test our changelogs before hitting a real DB. Unfortunately that mongo-java-server doesn't support the setting of the "ReadConcern" that's happening in Mongock. It works with Mongock BOM 4.1.19 but not with any 4.3.x.

**Comment by dieppa** [comment]
Thanks @abobwhite  and @scottfrazer . Jus to keep you updated, we are already working on this. We expect to have a release at the end of this week.
Thanks

**Comment by dieppa** [comment]
Hello @scottfrazer  and @abobwhite ,

sorry for the delay. This is already done in the version 4.3.5, please could you try. We haven't still document it but meanwhile, I paste a piece of configuration that illustrates how to do it.

```yaml
mongock:
  change-logs-scan-package:
    - com.github.cloudyrock.mongock.changelogs.client
  trackIgnored: true
  mongo-db:
    write-concern:
      w: majority
      w-timeout-ms: 300000
      journal: false
    read-concern: majority
    read-preference: primary
``` 

As it has the spring configuration processor, the IDE will probably suggest the values. The only that is free text is mongo-db.write-concern.w, which should be any value that MongoDB accepts for it.

Any question, please, let us know

**Comment by scottfrazer** [comment]
seems to work, thanks!

**Comment by erre-k-erre** [comment]
@abobwhite, did you get this working with mongo-java-server? I am using version 1.41.0 and still falling in the same issue with different values of the read-concern property.

**Comment by dieppa** [comment]
Version 1.41.0 of Mongock?
