### ISSUE TITLE
Inject spring beans in changelogs

### ISSUE THREAD

**Issue by santam85** [cloudyrock/mongock#300]
I am building a changelog that needs some external information to remap data.
I'd like to inject a Bean from the application context to retrieve this informaton, but if I follow the instructions at https://www.mongock.io/injecting-custom-dependencies-to-changesets the application fails to start:
`Error in method [...] Wrong parameter[BeanClass]`
What am I doing wrong? Is it because my bean is not a Repository?

**Comment by dieppa** [comment]
Hello @santam85 ,

Is this issue still on going or it's already resolved? If so, can you tell me what you did? It could be useful for other users.


Thanks

**Comment by santam85** [comment]
The issue is still present, even after adding the annotation you suggested to the changelog parameter. I can work around it by instantiating a new bean, but that's not ideal.
RestTemplate is not an interface, it is indeed the Spring RestTemplate as you guessed. I'd like to be able to use standard Spring dependency injection within Changelogs.

**Comment by dieppa** [comment]
"You'd like to be able to use standard Spring dependency injection within the ChangeLogs", no. You HAVE to be able 😄 

So don't worry, I will take a look at it and see what it's going on. If It's not something you are doing done, which would probably mean the documentation is not right and clear enough, it's a bug. I will try to tell you something by tomorrow.

**Comment by dieppa** [comment]
Hello @santam85 ,

sorry for the delay, we have been busy on other highly priority tasks.

We have tried to reproduce your issue, in the example apps, but it works fin. Please take a look spring-data-3 example project, this [line](https://github.com/cloudyrock/mongock-examples/blob/734bb8e6941f7b7ea30796649dc4bf11151ec0ce/mongoDB/version4_x/spring5-springdata3/src/main/java/com/github/cloudyrock/mongock/changelogs/client/initializer/ClientInitializerChangeLog.java#L19) specifically.

Feel free to play around to try to reproduce the issue.

We are using Mongock 4.3.7(latest release)

**Comment by dieppa** [comment]
hello @santam85 ,

we like to keep the issues list as clean as possible. Can you tell me if this is still relevant?

Cheers

**Comment by santam85** [comment]
I tried exactly like in your example, but no luck. I'll try to create a minimal reproduction example.

**Comment by dieppa** [comment]
OKk, please , try to reproduce it and share it with me, so I can figure out what exactly is going on. and fix your issue 😃

**Comment by dieppa** [comment]
@santam85  have you been able to reproduce it?

**Comment by santam85** [comment]
I was able to figure out what was happening: that error is shown also if no bean is found. I recommend a more explicit error in that case (or perhaps let Spring throw on the missing bean somehow?)

**Comment by dieppa** [comment]
Cool. Thanks for the suggestion, I think it's the right approach.

**Comment by Tripleo001** [comment]
I am currently battling this issue. please help

**Comment by dieppa** [comment]
@Tripleo001 , this wasn't really a issue, but a wrong use and the error feedback wasn't clear to know what needed to chage.

Can you provide the error trace, so we can help?
