### ISSUE TITLE
Getting LockPersistenceException in distributed env. What is the best lock strategy to use to avoid this exception.

### ISSUE THREAD

**Issue by manishpurohit92** [cloudyrock/mongock#310]
**Describe the bug** 

**MONGOCK ERROR**:

We have a service that is deployed over 20 VMs and each VM has 2 instances. During deployment, we used to run mongock migration on each instance. Service is not getting up on Some of the VMs due to this exception. 
Caused by: **io.changock.driver.api.lock.LockCheckException: MaxTries(3) reached due to LockPersistenceException**:
The average deployment time to bring service up is 10min.

As per the error, the application is not able to acquire a lock for **mongock** to start **migration**. 

Currently, we have a default lock mechanism.

**SpringDataMongoV3Driver driver = SpringDataMongoV3Driver.withDefaultLock(new MongoTemplate(mongoClient, database));**

What is the best lock strategy to use to avoid this exception?  

mongock-spring-v5 : <version>4.1.19</version>
mongodb-springdata-v3-driver : <version>4.1.13</version>
mongock-bom: <version>4.0.2.alpha</version>

Logs:

ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'changockSpring5' defined in class path resource [*.class]: Invocation of init method failed; nested exception is io.changock.migration.api.exception.ChangockException: io.changock.driver.api.lock.LockCheckException: MaxTries(3) reached due to LockPersistenceException:
current lock:  io.changock.driver.core.lock.LockEntry@401d83ce
new lock: Document{{$set=Document{{key=DEFAULT_LOCK, status=LOCK_HELD, owner=a30673e3-3f34-4d02-b923-6da93406fc2d, expiresAt=Mon Feb 22 04:11:23 UTC 2021}}}}
acquireLockQuery: And Filter{filters=[Filter{fieldName='key', value=DEFAULT_LOCK}, Filter{fieldName='status', value=LOCK_HELD}, Or Filter{filters=[Operator Filter{fieldName='expiresAt', operator='$lt', value=Mon Feb 22 04:08:23 UTC 2021}, Filter{fieldName='owner', value=*}]}]}
db error detail: WriteError{code=11000, message='E11000 duplicate key error collection: reports.mongobeelock index: mongobeelock_key_idx dup key: { : "DEFAULT_LOCK" }', details={}}

**Comment by dieppa** [comment]
Hello @manishpurohit92 ,

I am afraid the information provided is not enough to diagnose your issue. Please follow [this template](https://github.com/cloudyrock/mongock/issues/new?assignees=&labels=&template=bug_report.md&title=) to raise an issue, so we can help you 😃

**Comment by manishpurohit92** [comment]
@dieppa  I updated the ticket as per format. please guide me if something is missed.

**Comment by dieppa** [comment]
Thanks,

I see the versions of Mongock you are bringing are not right. There may be other issues too, but please, first update your project to use mongock-bom:4.3.7 and don't need to specify the version for the runner and driver, as the bom set up the versions for them. Please te a look to our [tutorial](https://www.mongock.io/quick-start). and let me know if your issue remains.

**Comment by manishpurohit92** [comment]
Thanks, for the quick reply.  and what about this 
**SpringDataMongo3Driver driver = SpringDataMongo3Driver.withDefaultLock(new MongoTemplate(mongoClient, database));**

what lock strategy would you suggest for multiple instances?

**Comment by dieppa** [comment]
In general, the recommended "lock strategy" is the default. If you want to tune it, please a look to [this part of the documentation](https://www.mongock.io/lock-1) that explain the lock configuration.

PD: I don't understand **We have a service that is deployed over 20 VMs and each VM has 2 instances**. Does that mean you have a service replicated around 40 times , 20 VMs x 2 instances? Or you have 20 services in replicated twice(2 instances) in a VM each?

**Comment by manishpurohit92** [comment]
@dieppa  It means 20 VMs x 2 instances, 40 instances of a single service. So each instance is waiting to get a lock. and as default **maxWaitingForLockMinutes** is 4min. after that time, the service is throwing this exception.  So I think, I would need to tune it.

**Comment by dieppa** [comment]
OK, so I can assume that you will have one instance performing the migration agains 39 idle instances, right?

Can you afford deploy those 39 instances, and ready, while the migration is still on going? If so, I would set the field **throwExceptionIfCannotObtainLock** to false, so the 39 instances doesn't wait for the lock.

If not, I would increase the field **maxWaitingForLockMinutes**, more or less matching the time taken but your migration, setting **maxTries** to two(worthy re-trying, but no reason for trying 3 times, in this case).

Play around with those properties according the size of your migration and let me know how it goes.

**Comment by manishpurohit92** [comment]
@dieppa  will do. Thanks for support
