### ISSUE TITLE
Calling migration script from scheduled task

### ISSUE THREAD

**Issue by aggo** [cloudyrock/mongock#312]
Hi, I would like to call one of the migration scripts that I wrote from a scheduled task. However, the @ChangeSet method requires a MongoDatabase as a parameter and I am not sure how to send it from inside my scheduled task. I tried autowiring MongoDatabase in my ScheduledTasks class and then sending it to the migration script method as parameter, but Spring complains that MongoDatabase is not a recognized bean. Any advice about how to proceed about this would be appreciated. Thank you :)

**Comment by aggo** [comment]
I found the solution: I can autowire MongoTemplate inside my ScheduledTasks class and do mongoTemplate.getDb() and pass that to the script :)

**Comment by dieppa** [comment]
Hello @aggo ,

I see you found the solution, but I would like to help you by confirming is the right approach.

What Mongock's version are you using? Long time ago we removed the MongoDatabase mandatory parameters in changeSets, no you can use whatever you want(except for MongoTemplate, for which you need to use MongockTemplate, which is just a kind of decorator for MongoTemplate).

Please see our [documentation](https://www.mongock.io)

**Comment by aggo** [comment]
Hi @dieppa, we are using 4.1.8, but we have code of our own that is used by the migration scripts that uses the MongoDatabase and changing it would be too much work at this point. However, will keep in mind the idea with MongockTemplate, thank you for always being so quick to answer the stuff posted here :) Kudos for the good work!

**Comment by dieppa** [comment]
Great and thanks! I don't fully understand your scenario, but keep into account that even using the mongodatabase, you should get it from MongockTemplate, as otherwise won't be synchronised properly with the lock.

Cheers

**Comment by aggo** [comment]
Oh, yes, thank you for re-mentioning that. Will do it as such. :)
