### ISSUE TITLE
Change set is being executed if the end system version is equals to its system version

### ISSUE THREAD

**Issue by jonaslins** [cloudyrock/mongock#313]
If a change set **A** with  its system version "1.3.4" and the end system version is "1.3.4", the **A** change set will be executed. Although the [documentation](https://www.mongock.io/changelogs) suggests that this changeSet wouldn't be executed because the end system version **is not** inclusive.

I have forced the if condition on the [isChangeSetWithinSystemVersionRange method of the ChangeLogService class on line 178 ](https://github.com/cloudyrock/mongock-core/blob/938b1141dc43ebacd5d643e8280127b6ce1085fb/mongock-runner/mongock-runner-core/src/main/java/com/github/cloudyrock/mongock/runner/core/executor/ChangeLogService.java#L178)to:
`version.compareTo(startSystemVersion) >= 0 && new DefaultArtifactVersion("1.3.4").compareTo(new DefaultArtifactVersion("1.3.4")) <= 0` and the result is true and the change method is included.

My mongock dependencies and versions are:

implementation("com.github.cloudyrock.mongock:mongock-spring-v5")
implementation("com.github.cloudyrock.mongock:mongodb-springdata-v3-driver")

mavenBom("com.github.cloudyrock.mongock:mongock-bom:4.3.4")

Is this implementation the correct behavior or is the doc just not updated?

**Comment by dieppa** [comment]
Hello @jonaslins ,

thank you and good point. It seems that actually the error is in the documentation as now your bugfix breaks a test to specific run the range inclusively(You can see it [here](https://github.com/cloudyrock/mongock-core/pull/115/checks?check_run_id=2188958730#step:4:2119))

At this point, I think that we better fix the documentation, otherwise we could potentially break some projects out there already using the systemVersion range inclusively.

Feel free to make pool request to [Mongock documentation project](https://github.com/cloudyrock/mongock-documentation). Alternatively, if you can't or wan't, we'll do it.

Thanks again for pointing this out 😄 

```
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.05 s <<< FAILURE! - in com.github.cloudyrock.mongock.runner.core.ChangeLogServiceTest
Error:  com.github.cloudyrock.mongock.runner.core.ChangeLogServiceTest.shouldReturnOnlyChangeSetsWithinSystemVersionRangeInclusive  Time elapsed: 0.019 s  <<< FAILURE!
java.lang.AssertionError: expected:<3> but was:<2>
	at com.github.cloudyrock.mongock.runner.core.ChangeLogServiceTest.shouldReturnOnlyChangeSetsWithinSystemVersionRangeInclusive(ChangeLogServiceTest.java:149)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    ChangeLogServiceTest.shouldReturnOnlyChangeSetsWithinSystemVersionRangeInclusive:149 expected:<3> but was:<2>
[INFO] 
Error:  Tests run: 60, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
```

**Comment by jonaslins** [comment]
Cool! I'll fix the documentation then! The current doc is actually the behavior of the mongock version 3. We got this inconsistency because of our internal PR checklist when there's a new migration on the pipeline.

**Comment by jonaslins** [comment]
Anyways. I think the inclusive behavior is better and more natural than the old one. It has always caused a bit of confusion.

**Comment by dieppa** [comment]
Yes, I also think that makes more sense to provide the range you want to include.

Thanks @jonaslins

**Comment by dieppa** [comment]
Fixed in documentation
