### ISSUE TITLE
[Feature Request] Add the hostname of executor in collection mongockChangeLog

### ISSUE THREAD

**Issue by olivierboudet** [cloudyrock/mongock#316]
Sometimes, we have issues and we need to know which instance executed the changelog.
Would it be possible to have the hostname saved in the collection mongockChangeLog ?

If it is a good idea, I can try to send a PR.

**Comment by dieppa** [comment]
Hello @olivierboudet,

 I like your idea, it sounds interesting and helpful. Thanks. 
 
 However, please explain me how you are thinking to do it, so we agree before you invest your time 😄
