### ISSUE TITLE
ChangeSet with "runAlways = true" is inserting duplicate records in changelog each time when migration is triggered

### ISSUE THREAD

**Issue by dhavaamar** [cloudyrock/mongock#322]
**Describe the bug** 

After upgrading Mongock to 4.1.19, the ChangeSet with "runAlways = true" param is inserting duplicate records each time when migration is triggered. Actually it should only execute the ChangeSet and not insert any change log.

**To Reproduce**

Steps and conditions to reproduce the behavior:
 - Steps
    - Upgrade Mongock to 4.1.19.
    - Trigger migration with ChangeSet having "**runAlways = true**" param.

![image](https://user-images.githubusercontent.com/81572944/112850969-2398af80-90c8-11eb-81cf-8b62e48f5787.png)

**Expected behavior**

The ChangeSet with "runAlways = true" param should be executed always, but it should not insert any records in changelog if its already exists.

![image](https://user-images.githubusercontent.com/81572944/112852649-c00f8180-90c9-11eb-9089-adcb899ebb69.png)

**Comment by dieppa** [comment]
thanks @dhavaamar , We'll take a look a it in the next days 😃

**Comment by osantana85** [comment]
Hi @dhavaamar, released in version 4.3.8. Please can you take a look and let me know. Thanks.
