### ISSUE TITLE
Encourage encapsulation in Mongock

### ISSUE THREAD

**Issue by dieppa** [cloudyrock/mongock#35]
Make setters package-private for those fields which shouldn't be changed once built

**Comment by mbuccat** [comment]
Hello @dieppa,
I'd like to help with this

**Comment by mbuccat** [comment]
Thanks for the tips! I'll go with your suggested approach

**Comment by dieppa** [comment]
Yeah, Actually I was about to tell you, as there is another person who wants to help with the  [refactor issue](https://github.com/cloudyrock/mongock/issues/36)

**Comment by mbuccat** [comment]
@dieppa 
I've changed the access modifiers for the setters. Awaiting more information about refactoring.

**Comment by dieppa** [comment]
@mbuccat , If your change covers this issue, please open a pull request(from your forked repository) and I review it. It should be pretty easy one. Thanks
