### ISSUE TITLE
having difficulties  in mongock migrations

### ISSUE THREAD

**Issue by chgayatri214** [cloudyrock/mongock#362]
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.github.cloudyrock.mongock.runner.core.executor.ChangeLogService.buildChangeLogObject(ChangeLogService.java:130)

The following method did not exist:

    com.github.cloudyrock.mongock.ChangeLogItem.<init>(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/util/List;)V

facing this issue when trying to migrate mongodb

**Comment by dieppa** [comment]
Hello @chgayatri214 ,

We don't have enough information to get an idea of what possible could be wrong.

Please see [this template for issues](https://github.com/cloudyrock/mongock/issues/new?assignees=&labels=&template=bug_report.md&title=)



At least, provide:
- mongock version
- using any framework?
- using annotation or builder?
- your changeLogs. We don't need the logic inside the changeSets, you can remove that but the class and how the changeSets are defined

...we may ask for something more later, but we would initially need that.

Cheers

**Comment by chgayatri214** [comment]
implementation group: 'com.github.cloudyrock.mongock', name: 'mongock-core', version: '5.0.1.BETA', ext: 'pom'

	implementation 'com.github.cloudyrock.mongock:mongock-bom:5.0.2.BETA'
	implementation 'com.github.cloudyrock.mongock:mongock-spring-v5:4.3.13.BETA'
	implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:5.0.2.BETA'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

	implementation group: 'org.mongodb', name: 'mongodb-driver-sync'

this is what i have in build .gradle  and 

i use @EnableMongock (Annontation approach) 

@ChangeLog
public class DatabaseChangeLog {
    @ChangeSet(order = "001", id = "seedDatabase", author = "gs")  


application.properties : 
mongock.change-logs-scan-package=com.example.mongodb.config

**Comment by chgayatri214** [comment]
databasechangeLog is in  that com.example.mongodb.config

**Comment by dieppa** [comment]
Hello again, please provide the method signature for the changeset:
`@Changeset(order = "001", id = "seedDatabase", author = "gs")`


As said, I actually need the entire class, but you can remove the actual conde in the methods. The reason for that is because there are some important facts like. Is there a constructor with parameters? Which parameters are you pasing to the methods, etc.

On the other hand, you are aware you are using the BETA version, right? Should work though, but still is a BETA 😉

**Comment by chgayatri214** [comment]
package com.example.mongodb.config;

import com.example.mongodb.model.Employee;
import com.example.mongodb.repository.EmployeesRepository;
import com.github.cloudyrock.mongock.ChangeLog;
import com.github.cloudyrock.mongock.ChangeSet;

import java.util.ArrayList;
import java.util.List;

@ChangeLog(order = "001")
public class DatabaseChangeLog {
    @ChangeSet(order = "001", id = "seedDatabase", author = "gs")
    public void seedDatabase(EmployeesRepository employeeRepository) {
        List<Employee> employees = new ArrayList<>();
        employees.add(createEmployee("1","smith","j","s@gmail.com", Employee.Gender.MALE,false));
        employees.add(createEmployee("2","john","k","j@gmail.com", Employee.Gender.MALE,true));
        employees.add(createEmployee("3","milli","s","m@gmail.com", Employee.Gender.FEMALE,true));
        employees.add(createEmployee("4","san","p","sa@gmail.com", Employee.Gender.MALE,true));
        employeeRepository.insert(employees);
    }

    private Employee createEmployee(String id, String first_name, String last_name, String email, Employee.Gender gender,boolean isPermanent) {
        Employee employee = new Employee(id,first_name,last_name,email,gender,isPermanent);
        return employee;
    }
}

Oh Ok this is my entire class  and iam new to monodb.

**Comment by dieppa** [comment]
ok, it seems you are using the wrong runner dependency(`mongock-spring-v5`).

If you want to keep using the BETA version, which I don't really recommend as we may change things like artifact and classes names, you should use this:
`com.github.cloudyrock.mongock:mongock-springboot:5.0.3.BETA-SNAPSHOT`

However I recommend to stick to the version 4.3.8, which is the latest stable and wait until we release version 5 with all the documentation you need.

**Comment by chgayatri214** [comment]
sure i will try  to use and let you know

**Comment by chgayatri214** [comment]
Thanks issue was resolved once i use 4.3.8
