### ISSUE TITLE
Can't find MongockBuilder in verion mongock-core:4.3.8 anymore

### ISSUE THREAD

**Issue by coderDem** [cloudyrock/mongock#371]
Hello,

we have updated our mongock-core from 3.3.2 to 4.3.8 but here I can't find MongockBuilder anymore?
Is this Builder still existing and were we can find it?

Best Regards

**Comment by dieppa** [comment]
Hello @coderDem ,

- for mongock standalone use `com.github.cloudyrock.standalone.MongockStandalone.builder()`
- fro spring use: `com.github.cloudyrock.spring.v5.MongockSpring5.builder()`

For more information please take a look to our [documentation](https://www.mongock.io/quick-start)

### Anyway, we are gonna release a RC or the version 5 soon, next weeks. I highly recommend to wait for it

**Comment by coderDem** [comment]
Thank you :-)
