### ISSUE TITLE
Support policy for mongo java drivers 4.1, 4.2 or 4.3 ?

### ISSUE THREAD

**Issue by gaelcrova** [cloudyrock/mongock#379]
Hi,

From https://www.mongock.io/compatibility-versions-table I can see that you are supporting 4.0.5 version of the mongodb java driver.
Is there any official support for 4.1, 4.2 or 4.3 drivers ? (required to support MongoDB 4.4.x) https://docs.mongodb.com/drivers/java/sync/current/compatibility/

Thanks

**Comment by dieppa** [comment]
Hello, 

currently we haven't update the libraries in the driver for version4. But I believe you can safely use at least 4.2.3. We haven't tested with higher versions.  

Version 5, in it snext RC will be build on latest versions, plus we'll probably upgrade them in version 4 too.
 But that will happen next week.
 
 Regards

**Comment by gaelcrova** [comment]
Ok thanks. I'll wait for next week build then !

**Comment by gaelcrova** [comment]
Hi @osantana85 
Do you know if new release will be available soon ?
Thanks
