### ISSUE TITLE
Add jacoco support for local and sonarcloud analysys

### ISSUE THREAD

**Issue by dieppa** [cloudyrock/mongock#39]
Requirements:

- Provide jacoco initial configuration for multi-project
- Provide minimum threshold for test coverage(initially can be per project or shared)
- Provide support to run jacoco locally and make it fails if the minimum test coverage is not achieved

Initially all tests(unit and integration tests) are grouped together. But next step is separate them, so they can be analysed separately  and have different thresholds.

**Comment by dieppa** [comment]
Hi @Zomzog,
sorry but your pull request is not working with sonar:
```java
 mvn sonar:sonar \   
  -Dsonar.projectKey=com.github.cloudyrock.mongock \
  -Dsonar.organization=cloudyrock \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=8ce5eaecf68d52ab2942dd06a65bfc0dda9c4960
```
The error message is:

> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project mongock: Please provide compiled classes of your project with sonar.java.binaries property -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project mongock: Please provide compiled classes of your project with sonar.java.binaries property

I haven't gone into detail, but I can see you are setting jacoco like it were a single project, but it's not. It's a multi-project which requires a more advance configuration.

On the other hand, even if that had worked, it wouldn't have been enough(Probably my fault, I actually created the issue for myself and didn't provide much detail). Yeah, sure it would work in sonarCloud, but still external commiters need a way to check test coverage locally, as  travis doesn't provide support for external forked PR to run on sonarcloud securely.

**Comment by Zomzog** [comment]
https://sonarcloud.io/dashboard?id=com.github.cloudyrock.mongock%3Amongock

Looks good on with my own travis/sonar ids.

I've changed the configuration with this doc: https://docs.travis-ci.com/user/sonarcloud/

To check coverage locally, the easiest way will be to use the IDE coverage no?

**Comment by dieppa** [comment]
I don't remember the details, but I will have a look.

Regarding the local checking, the best way is  by running `mvn verify` and obtain jacoco report ;)
