### ISSUE TITLE
 Command failed with error 8000 (AtlasError): 'user is not allowed to do action [remove] on [mydb.mongockLock]' 

### ISSUE THREAD

**Issue by yonimoses** [cloudyrock/mongock#52]
Hi,
I'm getting this error when trying with mongodb srv URI.

Any ideas?

**Comment by dieppa** [comment]
Hello @yonimoses , can you fill a template for a bug with a bit more information on it?
You can see how report a bug in [here](https://github.com/cloudyrock/mongock/blob/master/community/CONTRIBUTING.md#reporting-bugs)

Notice, we haven't set up the FAQ page yet.

Thanks
