### ISSUE TITLE
Mongo SNAPSHOT not avalable on oss.sonatype snapshots repositories

### ISSUE THREAD

**Issue by sgrillon14** [cloudyrock/mongock#54]
I had this:
```
  <repositories>
        <repository>
            <id>sonatype-releases</id>
            <url>https://oss.sonatype.org/content/repositories/releases</url>
        </repository>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```

but you do not deploy on oss.sonatype snapshots repositories

Do you want any help for this?

**Comment by dieppa** [comment]
No it's fine, thatnks. Regarding [spring issue](https://github.com/cloudyrock/mongock/issues/53). If you don't tell which version of Mongock you are using, I can't help you

**Comment by dieppa** [comment]
@sgrillon14  I don't really understand this issue? As I can see in another comment, you are using 1.16.1, which is not a snapshot. 

However, I will use snapshot deployments for future breaking version. Actually current 2.0.0-BETA could have been deployed to snapshot repository

**Comment by sgrillon14** [comment]
My question is "How to use a -SNAPSHOT version in my project?"
