### ISSUE TITLE
Allow own changelog instances instead of newInstance

### ISSUE THREAD

**Issue by MatthewStrickland** [cloudyrock/mongock#62]
Currently unable to control the creation of the ChangeLog objects. It would be nice to use custom ones I can pass to the builder so I can add fields based on application configuration, or even use other mongo driver wrappers like Morphia (without relying on set method parameters)

I've tried on core and it seems not doable unless I'm missing something, I imagine this is easier with the spring version.

**Comment by dieppa** [comment]
Hi @MatthewStrickland , I don't fully understand your issue.

- What do you mean with "unable to control the creation of the ChangeLog objects"?

- Custom ones what?

I can guess you want to inject your own dependencies, but not sure.

Anyway, which framework are you using?

**Comment by MatthewStrickland** [comment]
Hi @dieppa 

Ideally I was hoping to do something like this:

```
@ChangeLog
@AllArgsConstructor
@NoArgsConstructor
public class DatabaseChangeLog {
        
        private Datastore datastore;  // morphia
        private EnvConfig config;     // application properties

        @ChangeSet(order = "001", id = "createInitialDatabase", author = "Matt")
        public void initial() {
           ...
        }
```

I'm using Picocontainer (and dropwizard) which could inject these if it managed the ChangeLog itself. Morphia isn't necessarily needed but I'd like to put in specific application properties based on environments. If there's another way then I'd be happy to try it.

**Comment by dieppa** [comment]
Hi @MatthewStrickland 

no, right now there is nothing for that, but it could be done. But please notice that the lock mechanism is based on proxing the database access, so the datasource should be injected via builder. Free injection of database access is not the approach to go.

**Comment by dieppa** [comment]
So, I suggest to use our templates to either create an [issue](https://github.com/cloudyrock/mongock/blob/master/community/ISSUE_TEMPLATE.md)
or an [enhance](https://github.com/cloudyrock/mongock/blob/master/community/ENHANCENMENT_TEMPLATE.md)

Then feel free to pick it yourself and raise a PR(if so, please make a comment in the ticket itself letting the rest know of us you're picking it) or someone in our team will do it
