### ISSUE TITLE
Add ability to use own ChangeLog implementations

### ISSUE THREAD

**Issue by MatthewStrickland** [cloudyrock/mongock#63]
### Description

Injecting own ChangeLogs into builder to control properties of the object.

Something like:

```
@ChangeLog
@AllArgsConstructor
@NoArgsConstructor
public class DatabaseChangeLog {
        
        private EnvConfig config;     // application properties

        @ChangeSet(order = "001", id = "createInitialDatabase", author = "Matt")
        public void initial() {
           ...
        }
```

### Specific scenario

Unable to specify specific safety provisions for my prod environment.

### PRIORITY

minor

### Potential issues or difficulties

Consumers of this library will need to be aware that the method level database accessors provide the locking mechanism and so need to be careful not to inject their own persistence implementations.

### Expected behavior

Fields in ChangeLogs won't necessarily be null anymore.

### PRIORITY

MINOR

**Comment by MatthewStrickland** [comment]
I'll try and make a PR for soon. Am I able to tag this? If not I was going to use core-module, enhancement

**Comment by dieppa** [comment]
Thanks @MatthewStrickland.

I suggest you to have a look at MongockBuilderBase. You will see how it creates the proxy for database conections(mongodatabase, DB, etc.). I will useful

**Comment by dieppa** [comment]
I have tagged it and assigned to you.

**Comment by MatthewStrickland** [comment]
@dieppa Thanks, do I have appropriate permissions to push/create a branch? I keep getting a 403:

**remote: Permission to cloudyrock/mongock.git denied to MatthewStrickland.**

**Comment by dieppa** [comment]
We use standard fork approach. Fork this repository, create a branch for this issue(feature/issue-63) and when you are done, make a PR. Github offers you to make the PR agains your master in your forked repository or to this repository.

Let me know if you have any issue with that ;)

**Comment by MatthewStrickland** [comment]
Anyone else is free to take this one on!
