### ISSUE TITLE
Injections in SpringBoot monitored by the lock

### ISSUE THREAD

**Issue by dieppa** [cloudyrock/mongock#65]
### Description

The ability to inject spring dependencies via context was added as enhancement(Spring boot), but there MongoTemplate, MongoDatabase and DB are not being proxied, so the lock mechanism is not guaranteed .

### PRIORITY
CRITICAL

### Specific scenario
Using spring boot

### Behaviour

**Expected behaviour:** 
Injected MongoTemplate, MongoDatabase and DB being proxied(monitored)

**Actual behavior:** 
Injected MongoTemplate, MongoDatabase and DB are not proxied(monitored)

**Reproduces how often:** 
100%

### Version

All versions of Spring boot up to 2.0.1

### Link to repository using Mongock

[While no mandatory, accessing to the real code that uses Mongock, would help to solve the issue]

### Additional Information

Springboot shouldn't be used until fix

**Comment by gjeanmart** [comment]
Hi,
Is there any ETA on this issue or workaround to inject a dependency in the ChangeLog ? 
Thanks
Greg

**Comment by dieppa** [comment]
Hi, @gjeanmart .

this will be done over the weekend, so you can expect having it fixed by Monday.

**Comment by dieppa** [comment]
Actually some chances, to have it fixed tomorrow, but I cannot commit to that.

**Comment by gjeanmart** [comment]
Cool thanks !

**Comment by dieppa** [comment]
By the way, may I ask what dependencies are you injected via context? Because if you are using mongotemplate, you don't need to use SpringBoot module, you can use just Spring.

**Comment by gjeanmart** [comment]
I'm basically trying to use a Spring bean injected via `@Autowire` within a ChangeLog like this:
```
@ChangeLog
public class MyChangeLog {

    @Autowire
    private MyService myService;

    @ChangeSet(order = "001", id = "migration_x", author = "gjeanmart")
    public void migrationX(final MongoTemplate template) {

        Objects.requireNonNull(service, "MyService cannot be null");
        
        template.findAll(MyObject.class, "myCollectionForObject")
            .stream()
            .map(obj -> {
                obj.setNewField(myService.get(obj.id).afield);
                return obj;
          }).forEach(template::save);
    }
}
```

This currently fails because `myService` is `null`.

But after reading more carefully the issue details, it actually seems to be something else "The injections are not monitored by the lock" which might completely unrelated to this...

Sorry for being out of topic here. But is there any way to inject bean via `@Autowire` in a ChangeLog?

Thanks

**Comment by dieppa** [comment]
You are right. What you are concerned it's not what the bug is about. To inject your dependencies, you don't need to autowire them. As long is in spring context, you just need to add them as parameter to your changeSet method.


The bug is relate to montoTemplate. In SpringBoot module, is not monitored by the lock. So even if you weren't concerned, this bug is affecting you. But as mentioned, this will be fixed soon.

**Comment by dieppa** [comment]
@gjeanmart sorry, but we haven't been able to deliver the new version yet. We had to face some unexpected issues. 

We expect to have the new version tomorrow.
