### ISSUE TITLE
Versioning for ChangeLogs

### ISSUE THREAD

**Issue by SaschaWiegleb** [cloudyrock/mongock#82]
Is there any possibility to tag my change-logs with a version?

I would like to keep my change-logs for multiple DB upgrades and just execute the ones which are needed to upgrade from my current to the latest version.

This will be unnecessary complicated with just using the "changeLogsScanPackage" as grouping of the change-logs:
1. group all change-logs per version in separate packages
2. create multiple MongockBuilder
3. execute all of them which are between the current and the target version

Beside of that by using the history of applied change sets (stored in a collection called dbchangelog)
I need to pre fill the collection with the outdated change-sets to avoid running them.

**Comment by SaschaWiegleb** [comment]
Or would you suggest to 
1. group all change-logs per version in an separate packages
2. create multiple MongockBuilder
3. execute all of them which are between the current and the target version
?

**Comment by dieppa** [comment]
Hi @SaschaWiegleb , sorry II don't see anything you cannot do with the existing solution, but that may be because I don't fully understand your needs. Can you provide an example or scenario so I can understand a bit better?

Thanks

**Comment by SaschaWiegleb** [comment]
Hi @dieppa, thanks for your fast reply.
Imagine a product which checks the schema on startup, if any changes need to be applied.

Here are my two scenarios:
First: customer gets version 2.0 of a product and don't want to run the schema changes from 1.0 to 2.0 on first start because they are already inside the shipped version.

Second: Customer wants to upgrade from version 2.0 to 3.0, so just the change-sets between these two version needs to be applied to the DB.

If both would use the product since version 1.0 everything would be fine fine.

I imagine something like tagging a ChangeSet or ChangeLog with a version.
And providing a current DB version and a target DB version on execution.
So that mongock just executes the changes between these versions.

The default behavior could stay the same like it is currently.

Hopefully this helps to understand my need.

**Comment by dieppa** [comment]
Hi @SaschaWiegleb,

I think I understand your need, but we need to see it in more details. Right now we are not able to provide this features as quick as we wish, but we have taken note and we'll provide it.

Alternatively, if you think you know how to do it, feel free to raise a PR. We'll be more than happy to review it and add it to the next release.

Thanks

**Comment by SaschaWiegleb** [comment]
Ok I will try to contribute it. 
I will let you now, if I need help.

**Comment by dieppa** [comment]
Great, if anything come up, happy to help :)

**Comment by dieppa** [comment]
@SaschaWiegleb  this has been release in version 3.0.1.BETA

**Comment by dieppa** [comment]
@SaschaWiegleb I close this issue. Please let me know if you have any other issue

**Comment by SaschaWiegleb** [comment]
Thank you, If I face something else I will let you know.
