### ISSUE TITLE
Display more meaningful logs when applying changes

### ISSUE THREAD

**Issue by grabarczyk-t** [cloudyrock/mongock#84]
Logs displayed when applying changes are not helpful. They show something like that: `com.github.cloudyrock.mongock.ChangeEntry@66a3c1f8 applied` which does't say which change it refers to. It would be better if it included more meaningful information, like the change id

**Comment by dieppa** [comment]
That totally makes sense. That's due of lack of 'toString()' implementation for some classes. We'll improve that and let you know when release it in a new BETA version. I would say today or tomorrow

**Comment by dieppa** [comment]
This is ready to be released in 3.0.2.BETA, but nexus server is out of service. We'll try it again tomorrow.

 [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy (injected-nexus-deploy) on project mongock: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy failed: Nexus connection problem to URL [https://oss.sonatype.org/ ]: 503 - Service Unavailable -> [Help 1]

**Comment by dieppa** [comment]
@grabarczyk-t It has been released 3.0.3.BETA with improved logs.
I close this issue. If you fine anything else, please let us know.
Thanks
