### ISSUE TITLE
versioning and runAlways issues

### ISSUE THREAD

**Issue by wirefreethought** [cloudyrock/mongock#86]
How is the versioning supposed to work? If I update the change-set version (in the annotation), it is NOT being re-executed. I do have the builder set with the correct start/end version range.

**Comment by wirefreethought** [comment]
Ah. Looking at the code, it appears that an updated version will be ignored if runAlways=false. This seems wrong.

**Comment by dieppa** [comment]
Hello @wirefreethought , thanks for test the Mongock beta version.
I am not sure I follow you. Could  you provide a more precise example with the steps and values, like:
1) Create changeset 
2) run mongock
3) add version with value 2
4) run mongock with builder and version range 0,2
...

**Comment by wirefreethought** [comment]
Hi @dieppa. Here are the steps:

1. Create changeset with version 1
2. Run mongock with version range 0,2 [changeset executed]
3. Update changeset to version 1.5
4. Run mongock with version range 0,2 [changeset NOT executed]
5. Update changeset to runAlways=true
6. Run mongock with version range 0,2 [changeset is now executed]

My question is why is it necessary to set runAlways=true if the version has changed? To me, it seems like it should be implicit that the changeset should be re-executed if the version has been updated, regardless of runAlways.

**Comment by dieppa** [comment]
Ahhh ok, I got your question now. Ok, the problem is probably that the readme doesn't explain the concept as good as it should. Sorry about that.

So this version is not the versión of the changeset like that. I like that idea, but currently can be achieved by other mechanisms. This version is from a consultancy point of view. They use their product in several customers, with diferente version of the product. They will apply the database changes depending on the version of the product. So you tag the changeset with the version of the product and then, when building Mongock you specify which version range you want to apply.

As I thought this wouldn't be easier for users to understand, it hasn't been officially released and it's in BETA, so we may change some aspects of the API such more clear names, or any improvement we(and users) may find interesting.

Do you have any suggestion?

**Comment by wirefreethought** [comment]
@dieppa Yes, naming is everything. I think your idea of version is really more of a tag, like in git. You want to tag change-sets for different customers. This would be independent of the concept of versioning I'm referring to, which is really versioning of the data itself. So to summarize, I would propose the following changes:

- Change your existing ``version`` to ``tag`` and provide a way to execute change-sets for a specific tag. This should solve the business case you outline above.
- Keep the ``version`` annotation and start/end versioning logic, but make it independent of runAlways.

**Comment by dieppa** [comment]
I get your point. I think version for this concept is confusing, but tag is too. This is something that should be incremental and a tag doesn't need to be. I will come up with a better name though.

On the other hand, regarding the version you have in mind, I have some concerns:
1)  I don't think start/end makes sense here. As I see it, the logic should be as easy as: a changeset will run if is a new one, runAlways or its version is upgraded. Also it would apply to all changesets, which I don't think is right.

2) This can be easily achieved by adding the version to the changeset id. As changesets are identified by id, if you change it, it will run again.

**So, if you see a need for this "version", can you explain me why, so I can see it? And second, in case you do, do you still think that start/end is relevant?**

**Comment by wirefreethought** [comment]
@dieppa The reason for ``tag`` is because you mention certain change-sets should only apply to certain customers. Unless I misunderstood your use-case. So the tag would simply identify a given customer. Regarding ``version``, it is still useful over and above ``id``.  One reason is the id has to be unique across the change-log. So what if my ids all happen to be incremental numbers? If I bump some id in the middle, I now have to bump all the ones after. On the other hand, ``version`` only applies to a specific change-set. In other words, ``version`` is in effect scoped by the change-set's ``id``. This could come when change-sets are still being developed and tested as part of a roll-out to prod. As a change or addition to a given change-set is made, the developer would ideally bump its version. This way, other devs or qa could ensure that they get the change-set reapplied in their local env. We could achieve this by changing the change-set id, but as I explained above - due to possible collisions - that could be extremely cumbersome.

**Comment by dieppa** [comment]
No, I meant that you can name(assign id) with the label you wish **plus** a version, such as `myChangeSet-V1`, so to upgrade the version you can do `myChangeset-V2`. Having a version is definitely cleaner and the proper way, but I wouldn't like to overcomplicated if there is no really a need. **As a user would you appreciate this anyway?**


Regarding the tag, the requirement it's not actually that you want to apply the changeset to certain clients, but you want to apply the change depending on the version of the product your client is in. It's the version, but not  the changeset's version, it's the product's version that uses mongock. Anyway, I definitely see the name is confusing.

**Comment by wirefreethought** [comment]
Yes that's true, you could overload id with a version suffix. But yeah, I think have a numeric version would be cleaner. For one thing, I could then be free to make my ids alphanumeric or whatever. And I could have multiple versions of the same changeset (with the same id), and decide to apply one or the other, depending on the version of the code I'm on. (So in other words, roll-back.) But yes, it is more complicated.

**Comment by dieppa** [comment]
yeah, If I had used "sufix" since the beginning, it would have been easier to explain :D
Anyway, I like your view, and although it's more complicated is totally optional, so only if you need it, you take the "complication".

I will think about that as well the "tag" thing over the weekend. Will keep you updated, just in case you are interested.

Thanks again.

**Comment by wirefreethought** [comment]
Yes please keep me posted. Thanks for being so responsive. Great work here.

**Comment by dieppa** [comment]
sorry for this delay, but we have prioritised other issues. Anyway, we have renamed version to systemVersion, it's not clear but at least people don't think it's the changeSet version and for clarification , people have the README and javadoc. 
Thanks
