### ISSUE TITLE
Display time duration for every changeset

### ISSUE THREAD

**Issue by krasova** [cloudyrock/mongock#94]
Thanks you for the wonderful product! Is it possible to add one more column for mongockChangeLog collection and keep records of execution time for every changeset?

**Comment by dieppa** [comment]
Hello @krasova, that's actually a really good idea which is not hard to address. However we are quite tight right now. 

How urgent/important is that to your team? is preventing you from developing a feature or releasing a version? Are you using it in production? 

Thanks

**Comment by krasova** [comment]
It is very urgent since I working on performance testing right now and I want to see what is going with changsets execution time with different volumes of data.

**Comment by dieppa** [comment]
Ok. If you prefer, I can have a look later and tell you the how long you can expect to have a version with it. Does that work for you?

**Comment by krasova** [comment]
@dieppa cool, thanks!

**Comment by dieppa** [comment]
Hello @krasova  again.
I think I can have it for Wednesday. Probably much earlier, but I can't commit to that.

**Comment by dieppa** [comment]
Anyway, thinking about it. If it's that urgent, I believe you can do your own workaround by tracking how long each changeSet takes and write down to log or even to mongo.

...Just a suggestion in case it's veery urgent.

**Comment by krasova** [comment]
@dieppa Yes, thanks, I am doing this right now :-) but anyway It will be cool feature, flyway and other migration tools have this feature.

**Comment by dieppa** [comment]
Agreed and I happy you suggested as it's a good time =D

**Comment by krasova** [comment]
Probably, it will be good to have this info in the log as well. Something like this - 
APPLIED - Mongock change[changeSetName] for method[methodName] at Tue Nov 26 09:48:14 EST 2019 by krasova, **execution time  - 234 ms**

**Comment by dieppa** [comment]
yeah, that'd come for the same price :)

**Comment by dieppa** [comment]
Hello @krasova don't take it as commitment, but I think we can have this sorted out by the end of this week

**Comment by krasova** [comment]
Wonderful , thanks a lot!

**Comment by dieppa** [comment]
Said that I probably need a couple of days more. Hopefully by Wednesday

**Comment by dieppa** [comment]
Hello @krasova , sorry for this. 
Being realistic this week will be pretty hard as we have a deadline and the end of it. However, after this and before Christmas we'll be relieved, so I can commit on having this(as well as other small issues) at during next week, around Tuesday.

I hope this works for you.
Thanks

**Comment by krasova** [comment]
Cool, thanks!

**Comment by dieppa** [comment]
3.0.8.BETA
